export const fiveSecondPrompts: string[] = [
  "Name 3 countries in Asia",
  "Name 3 elements on the Periodic Table",
  "Name 3 US Presidents",
  "Name 3 planets in our solar system",
  "Name 3 characters from Harry Potter",
  "Name 3 brands of soda",
  "Name 3 European capital cities",
  "Name 3 types of pasta",
  "Name 3 sports that use a ball",
  "Name 3 colors in the rainbow",
  "Name 3 breeds of dogs",
  "Name 3 African countries",
  "Name 3 primary colors",
  "Name 3 Marvel superheroes",
  "Name 3 famous painters",
  "Name 3 types of fruit that are red",
  "Name 3 bones in the human body",
  "Name 3 musical instruments",
  "Name 3 languages spoken in Europe",
  "Name 3 ocean animals",
  "Name 3 internal organs",
  "Name 3 Disney movies",
  "Name 3 types of cheese",
  "Name 3 historical wars",
  "Name 3 Greek Gods",
  "Name 3 fast food chains",
  "Name 3 car manufacturers",
  "Name 3 layers of the Earth",
  "Name 3 Taylor Swift songs",
  "Name 3 items found in a bathroom",
  "Name 3 units of measurement",
  "Name 3 continents",
  "Name 3 things that fly",
  "Name 3 types of flowers",
  "Name 3 social media apps",
  "Name 3 countries that start with 'S'",
  "Name 3 mammals that live in water",
  "Name 3 pieces of furniture",
  "Name 3 board games",
  "Name 3 constellations",
  "Name 3 types of triangles",
  "Name 3 James Bond actors",
  "Name 3 parts of a plant",
  "Name 3 famous world landmarks",
  "Name 3 ingredients in a cake",
  "Name 3 genres of music",
  "Name 3 luxury fashion brands",
  "Name 3 flightless birds",
  "Name 3 items in a toolbox",
  "Name 3 video game consoles",
  "Name 3 countries with 'New' in their name",
  "Name 3 Nobel Prize winners",
  "Name 3 types of clouds",
  "Name 3 songs by The Beatles",
  "Name 3 Olympic sports",
  "Name 3 items found in a wallet",
  "Name 3 types of tea",
  "Name 3 desert animals",
  "Name 3 US States on the East Coast",
  "Name 3 kitchen appliances",
  "Name 3 Shakespeare plays",
  "Name 3 characters from Star Wars",
  "Name 3 types of snakes",
  "Name 3 prime numbers",
  "Name 3 famous inventors",
  "Name 3 things made of glass",
  "Name 3 words that rhyme with 'Blue'",
  "Name 3 types of weather",
  "Name 3 mountain ranges",
  "Name 3 Netflix original series",
  "Name 3 parts of a cell",
  "Name 3 movies starring Tom Hanks",
  "Name 3 ways to cook an egg",
  "Name 3 capital cities in South America",
  "Name 3 things that are yellow",
  "Name 3 species of sharks",
  "Name 3 famous scientists",
  "Name 3 punctuation marks",
  "Name 3 types of berries",
  "Name 3 countries in the Middle East",
  "Name 3 actors named 'Chris'",
  "Name 3 types of weather disasters",
  "Name 3 things you find at a beach",
  "Name 3 ingredients in a salad",
  "Name 3 world currencies",
  "Name 3 parts of a computer",
  "Name 3 things that are sticky",
  "Name 3 Pixar movies",
  "Name 3 types of whales",
  "Name 3 rivers in Europe",
  "Name 3 sitcoms from the 90s",
  "Name 3 historical empires",
  "Name 3 items of winter clothing",
  "Name 3 things that smell good",
  "Name 3 states in Australia",
  "Name 3 hobbies",
  "Name 3 flavors of ice cream",
  "Name 3 types of trees",
  "Name 3 breakfast cereals",
  "Name 3 world-famous bridges",
  "Name 3 items in a first aid kit",
  "Name 3 female singers",
  "Name 3 things that are sharp",
  "Name 3 types of rocks",
  "Name 3 Japanese cities",
  "Name 3 things you do at the gym",
  "Name 3 characters from Friends",
  "Name 3 colors on the Italian flag",
  "Name 3 items in a school bag",
  "Name 3 programming languages",
  "Name 3 countries bordering Germany",
  "Name 3 types of shoes",
  "Name 3 DC superheroes",
  "Name 3 elements that are metals",
  "Name 3 ways to say 'Hello'",
  "Name 3 things you find in a library",
  "Name 3 movie directors",
  "Name 3 types of soup",
  "Name 3 countries in North America",
  "Name 3 things made of wood",
  "Name 3 emergency services",
  "Name 3 components of a burger",
  "Name 3 famous poets",
  "Name 3 types of bread",
  "Name 3 things you see in the sky at night",
  "Name 3 animals with trunks or tusks",
  "Name 3 cities in Canada",
  "Name 3 types of nuts",
  "Name 3 Harry Potter houses",
  "Name 3 things that are cold",
  "Name 3 types of dance",
  "Name 3 US state capitals",
  "Name 3 things that are spicy",
  "Name 3 breeds of cats",
  "Name 3 types of fabric",
  "Name 3 countries in Central America",
  "Name 3 items in a makeup bag",
  "Name 3 things you find in a garage",
  "Name 3 rappers",
  "Name 3 pieces of jewelry",
  "Name 3 things you find in a park",
  "Name 3 types of bears",
  "Name 3 countries that start with 'B'",
  "Name 3 classic horror movies",
  "Name 3 things you find in a laundry room",
  "Name 3 types of wind instruments",
  "Name 3 European rivers",
  "Name 3 things that produce heat",
  "Name 3 movie franchises",
  "Name 3 items on a breakfast menu",
  "Name 3 things made of plastic",
  "Name 3 cities in England",
  "Name 3 types of monkeys",
  "Name 3 characters from The Avengers",
  "Name 3 things you see at a wedding",
  "Name 3 types of wine",
  "Name 3 brands of computers",
  "Name 3 countries in Scandinavia",
  "Name 3 items found in a toolbox",
  "Name 3 types of dinosaurs",
  "Name 3 things you find in an office",
  "Name 3 types of pasta shapes",
  "Name 3 famous queens",
  "Name 3 things you find in a purse",
  "Name 3 flavors of potato chips",
  "Name 3 US states that start with 'A'",
  "Name 3 things you do at a party",
  "Name 3 species of birds",
  "Name 3 things found in a nursery",
  "Name 3 types of fruit that have pits",
  "Name 3 things that are loud",
  "Name 3 brands of sneakers",
  "Name 3 countries that use the Euro",
  "Name 3 pieces of playground equipment",
  "Name 3 types of candy bars",
  "Name 3 characters from Disney's Lion King",
  "Name 3 things you find in a doctor's office",
  "Name 3 types of transportation",
  "Name 3 cities in Florida",
  "Name 3 things made of metal",
  "Name 3 types of lizards",
  "Name 3 brands of watch",
  "Name 3 things you find in a hotel room",
  "Name 3 famous explorers",
  "Name 3 types of cereal",
  "Name 3 things you find at a zoo",
  "Name 3 words that rhyme with 'Cat'",
  "Name 3 things that are green",
  "Name 3 parts of a car",
  "Name 3 types of insects",
  "Name 3 things you find on a farm",
  "Name 3 countries in South America",
  "Name 3 types of furniture in a bedroom",
  "Name 3 ingredients in a sandwich",
  "Name 3 things that are heavy",
  "Name 3 types of fish",
  "Name 3 things you find in a classroom",
  "Name 3 brands of chocolate",
  "Name 3 things you see at a circus",
  "Name 3 types of rodents",
  "Name 3 scientists who won a Nobel Prize",
  "Name 3 components of an atom",
  "Name 3 organs in the respiratory system",
  "Name 3 phases of the moon",
  "Name 3 types of electromagnetic radiation",
  "Name 3 famous explorers of the sea",
  "Name 3 ancient civilizations",
  "Name 3 types of simple machines",
  "Name 3 female authors",
  "Name 3 plays written by Shakespeare",
  "Name 3 Greek philosophers",
  "Name 3 countries that were part of the Roman Empire",
  "Name 3 famous nurses or doctors from history",
  "Name 3 types of poetic devices",
  "Name 3 books by Stephen King",
  "Name 3 Roman numerals",
  "Name 3 types of bridge structures",
  "Name 3 famous classical composers",
  "Name 3 tools used by a carpenter",
  "Name 3 things you do at an airport",
  "Name 3 types of martial arts",
  "Name 3 items used in a science lab",
  "Name 3 things that are waterproof",
  "Name 3 types of fuel",
  "Name 3 things that can be recycled",
  "Name 3 parts of a bicycle",
  "Name 3 types of percussion instruments",
  "Name 3 famous statues",
  "Name 3 things you find in a forest",
  "Name 3 types of grains",
  "Name 3 things that happen during a storm",
  "Name 3 Olympic swimming strokes",
  "Name 3 things you find in a desert",
  "Name 3 types of energy",
  "Name 3 things that have wheels",
  "Name 3 major world religions",
  "Name 3 things you do before going to bed",
  "Name 3 types of shellfish",
  "Name 3 things you find in a gym locker",
  "Name 3 ways to preserve food",
  "Name 3 things that grow underground",
  "Name 3 types of geometric shapes",
  "Name 3 things you find in a sewing kit",
  "Name 3 types of non-fiction books",
  "Name 3 things that produce a reflection",
  "Name 3 types of citrus fruit",
  "Name 3 things that can be folded",
  "Name 3 types of map projections",
  "Name 3 things you find in a movie theater",
  "Name 3 types of volcanic eruptions",
  "Name 3 things you find in a museum",
  "Name 3 types of competitive racing",
  "Name 3 things you find on a construction site",
  "Name 3 types of natural fibers",
  "Name 3 things that are transparent",
  "Name 3 types of winter sports",
  "Name 3 things you find in a hospital",
  "Name 3 types of human teeth",
  "Name 3 things you find in a toolbox",
  "Name 3 types of broadleaf trees",
  "Name 3 things you do on a Sunday",
  "Name 3 types of carnivorous plants",
  "Name 3 things you find at a bus stop",
  "Name 3 types of money (currencies)",
  "Name 3 things you find in a garden",
  "Name 3 types of spicy food",
  "Name 3 things you find in a refrigerator",
  "Name 3 types of primates",
  "Name 3 things you find in a cave",
  "Name 3 types of exercise",
  "Name 3 things you find in a drawer",
  "Name 3 types of software",
  "Name 3 things you find on a dinner table",
  "Name 3 types of poetry",
  "Name 3 things you find in a backpack",
  "Name 3 types of weather patterns",
  "Name 3 things you find at a gas station",
  "Name 3 types of craft hobbies",
  "Name 3 types of baked goods",
  "Name 3 things you find in a school",
  "Name 3 types of aquatic plants",
  "Name 3 things you find in a theater",
  "Name 3 types of medical specialists",
  "Name 3 things you find in a pharmacy",
  "Name 3 types of footwear",
  "Name 3 things you find at a carnival",
  "Name 3 types of cold-blooded animals",
  "Name 3 things you find in a kitchen",
  "Name 3 types of reptiles",
  "Name 3 things you find in a bedroom",
  "Name 3 types of candy",
  "Name 3 things you find in a living room",
  "Name 3 types of birds",
  "Name 3 types of cars",
  "Name 3 things you find in a basement",
  "Name 3 things you find in an attic",
  "Name 3 types of fruit",
  "Name 3 things you find in a grocery store",
  "Name 3 types of vegetables",
  "Name 3 things you find in a hardware store",
  "Name 3 types of meat",
  "Name 3 things you find in a toy store",
  "Name 3 things you find in a clothing store",
  "Name 3 types of jewelry",
  "Name 3 things you find in a pet store",
  "Name 3 types of animals",
  "Name 3 things you find in a bank",
  "Name 3 things you find in a post office",
  "Name 3 types of music",
  "Name 3 types of books",
  "Name 3 types of games",
  "Name 3 things you find in a stadium",
  "Name 3 types of sports",
  "Name 3 things you find in a swimming pool",
  "Name 3 types of art",
  "Name 3 things you find in a restaurant",
  "Name 3 types of food",
  "Name 3 things you find in a cafe",
  "Name 3 types of drinks",
  "Name 3 things you find in a bar",
  "Name 3 types of alcohol",
  "Name 3 things you find in a nightclub",
  "Name 3 types of people",
  "Name 3 things you find in a city",
  "Name 3 types of buildings",
  "Name 3 things you find in a village",
  "Name 3 types of houses",
  "Name 3 things you find in the ocean",
  "Name 3 types of islands",
  "Name 3 things you find on a mountain",
  "Name 3 types of mountains",
  "Name 3 types of deserts",
  "Name 3 types of forests",
  "Name 3 things you find in space",
  "Name 3 types of stars",
  "Name 3 things you find in the sky",
  "Name 3 things you find on the ground",
  "Name 3 types of soil",
  "Name 3 things you find in water",
  "Name 3 types of water",
  "Name 3 things you find in air",
  "Name 3 types of gases",
  "Name 3 things you find in fire",
  "Name 3 types of heat",
  "Name 3 things you find in light",
  "Name 3 types of light",
  "Name 3 things you find in sound",
  "Name 3 types of sound",
  "Name 3 things you find in time",
  "Name 3 types of time",
  "Name 3 things you find in life",
  "Name 3 types of life",
  "Name 3 things you find in death",
  "Name 3 types of death",
  "Name 3 things you find in love",
  "Name 3 types of love",
  "Name 3 things you find in hate",
  "Name 3 types of hate",
  "Name 3 things you find in war",
  "Name 3 types of war",
  "Name 3 things you find in peace",
  "Name 3 types of peace",
  "Name 3 things you find in a dream",
  "Name 3 types of dreams",
  "Name 3 things you find in a nightmare",
  "Name 3 types of nightmares",
  "Name 3 things you find in a thought",
  "Name 3 types of thoughts",
  "Name 3 things you find in a feeling",
  "Name 3 types of feelings",
  "Name 3 things you find in a memory",
  "Name 3 types of memories",
  "Name 3 things you find in a secret",
  "Name 3 types of secrets",
  "Name 3 things you find in a lie",
  "Name 3 types of lies",
  "Name 3 things you find in a truth",
  "Name 3 types of truth",
  "Name 3 things you find in a question",
  "Name 3 types of questions",
  "Name 3 things you find in an answer",
  "Name 3 types of answers",
  "Name 3 things you find in a word",
  "Name 3 types of words",
  "Name 3 things you find in a sentence",
  "Name 3 types of sentences",
  "Name 3 things you find in a story",
  "Name 3 movies starring Leonardo DiCaprio",
  "Name 3 types of cloud formations",
  "Name 3 characters from The Simpsons",
  "Name 3 countries in Oceania",
  "Name 3 components of a cell",
  "Name 3 80s pop stars",
  "Name 3 types of chess pieces",
  "Name 3 world-famous sculptures",
  "Name 3 parts of the human eye",
  "Name 3 winners of the FIFA World Cup",
  "Name 3 types of energy sources",
  "Name 3 items found in a spaceship",
  "Name 3 types of sushi rolls",
  "Name 3 songs by Queen",
  "Name 3 countries that border France",
  "Name 3 layers of the atmosphere",
  "Name 3 tools used by a surgeon",
  "Name 3 types of sharks",
  "Name 3 DC Comics villains",
  "Name 3 types of classical music composers",
  "Name 3 items found in a sewing kit",
  "Name 3 types of tea leaves",
  "Name 3 famous fashion designers",
  "Name 3 types of engineering",
  "Name 3 items found at a campsite",
  "Name 3 types of non-fiction book genres",
  "Name 3 characters from The Lord of the Rings",
  "Name 3 types of bridge designs",
  "Name 3 famous female scientists",
  "Name 3 things you see at a parade",
  "Name 3 types of pasta sauces",
  "Name 3 countries that start with 'I'",
  "Name 3 characters from SpongeBob SquarePants",
  "Name 3 items found in a science lab",
  "Name 3 types of social media filters",
  "Name 3 famous world leaders from the 1900s",
  "Name 3 types of exercise equipment",
  "Name 3 types of citrus fruits",
  "Name 3 countries in the Caribbean",
  "Name 3 types of programming languages",
  "Name 3 items found on a desk",
  "Name 3 types of dinosaur species",
  "Name 3 characters from Marvel's Avengers",
  "Name 3 types of precious stones",
  "Name 3 famous architects",
  "Name 3 items found in a gym locker",
  "Name 3 types of spicy peppers",
  "Name 3 countries that border India",
  "Name 3 types of human emotions",
  "Name 3 items found in a bakery",
  "Name 3 types of martial arts styles",
  "Name 3 famous painters from the Renaissance",
  "Name 3 items found in a hotel lobby",
  "Name 3 countries that start with 'P'",
  "Name 3 items found in a library",
  "Name 3 types of musical notation",
  "Name 3 famous world landmarks in Asia",
  "Name 3 types of breakfast cereals",
  "Name 3 items found in a hospital room",
  "Name 3 types of boat vessels",
  "Name 3 countries that are landlocked",
  "Name 3 items found in a kitchen drawer",
  "Name 3 types of geometric angles",
  "Name 3 famous American authors",
  "Name 3 items found at a construction site",
  "Name 3 types of birds of prey",
  "Name 3 types of card games",
  "Name 3 items found in a car's glovebox",
  "Name 3 types of constellations",
  "Name 3 famous explorers of the Americas",
  "Name 3 items found in a school classroom",
  "Name 3 types of winter weather",
  "Name 3 countries that start with 'R'",
  "Name 3 items found in a dentist's office",
  "Name 3 types of fabric textures",
  "Name 3 famous historical queens",
  "Name 3 items found in a post office",
  "Name 3 types of nocturnal animals",
  "Name 3 countries that border the Mediterranean Sea",
  "Name 3 items found in a vanity",
  "Name 3 types of dance genres",
  "Name 3 famous scientific inventions",
  "Name 3 items found in a jewelry store",
  "Name 3 types of renewable energy",
  "Name 3 items found at a hair salon",
  "Name 3 types of clouds in the sky",
  "Name 3 famous British monarchs",
  "Name 3 items found in a garden shed",
  "Name 3 types of farm machinery",
  "Name 3 countries that start with 'G'",
  "Name 3 items found in a nursery room",
  "Name 3 types of computer hardware",
  "Name 3 famous world capitals in Europe",
  "Name 3 items found in a bar",
  "Name 3 types of large cats",
  "Name 3 countries in Africa",
  "Name 3 items found in a briefcase",
  "Name 3 famous classical musicians",
  "Name 3 items found in a laundry room",
  "Name 3 types of insects with wings",
  "Name 3 countries that start with 'T'",
  "Name 3 items found in a purse",
  "Name 3 types of trees with needles",
  "Name 3 famous movie directors",
  "Name 3 types of citrus trees",
  "Name 3 items found in a garage",
  "Name 3 types of sea shells",
  "Name 3 famous Olympic athletes",
  "Name 3 items found in a pantry",
  "Name 3 countries that start with 'M'",
  "Name 3 items found in a backpack",
  "Name 3 types of flowers that are red",
  "Name 3 famous actors from the 90s",
  "Name 3 items found on a nightstand",
  "Name 3 types of fish found in the ocean",
  "Name 3 countries in Southeast Asia",
  "Name 3 items found in a bathroom cabinet",
  "Name 3 types of desert plants",
  "Name 3 famous songs from the 70s",
  "Name 3 items found in a messy room",
  "Name 3 types of snakes that are venomous",
  "Name 3 countries that start with 'L'",
  "Name 3 items found in a recycling bin",
  "Name 3 types of beans",
  "Name 3 famous historical inventors",
  "Name 3 items found in a junk drawer",
  "Name 3 countries in East Africa",
  "Name 3 items found in a refrigerator door",
  "Name 3 types of bread rolls",
  "Name 3 famous books by Charles Dickens",
  "Name 3 items found in a closet",
  "Name 3 countries that start with 'N'",
  "Name 3 items found in a diaper bag",
  "Name 3 types of summer fruits",
  "Name 3 famous comedians",
  "Name 3 items found in a craft store",
  "Name 3 types of indoor plants",
  "Name 3 countries that border Canada",
  "Name 3 items found in a toolbox tray",
  "Name 3 types of kitchen utensils",
  "Name 3 famous female singers from the 2000s",
  "Name 3 items found in an office lobby",
  "Name 3 types of cheese from France",
  "Name 3 countries in the Balkans",
  "Name 3 items found on a cruise ship",
  "Name 3 types of aquatic birds",
  "Name 3 famous movies from the 80s",
  "Name 3 items found in a hiking pack",
  "Name 3 types of tea ceremonies",
  "Name 3 countries that start with 'E'",
  "Name 3 items found in a makeup kit",
  "Name 3 types of architectural styles",
  "Name 3 famous paintings by Van Gogh",
  "Name 3 items found in a basement workshop",
  "Name 3 types of flightless birds",
  "Name 3 countries in West Africa",
  "Name 3 items found in a first-aid box",
  "Name 3 types of pasta noodles",
  "Name 3 famous sports teams from New York",
  "Name 3 items found in a desk drawer",
  "Name 3 types of rock music subgenres",
  "Name 3 countries that border the Baltic Sea",
  "Name 3 items found in a beach bag",
  "Name 3 types of edible seeds",
  "Name 3 famous landmarks in London",
  "Name 3 items found in a jewelry box",
  "Name 3 types of social media posts",
  "Name 3 countries that start with 'H'",
  "Name 3 items found in a coffee shop",
  "Name 3 types of weather forecasts",
  "Name 3 famous people from history named George",
  "Name 3 items found in a gym bag",
  "Name 3 types of winter coats",
  "Name 3 countries in the Himalayas",
  "Name 3 items found on a picnic blanket",
  "Name 3 types of sea life that glow",
  "Name 3 famous buildings in New York City",
  "Name 3 items found in a teacher's desk",
  "Name 3 types of craft beers",
  "Name 3 countries that start with 'K'",
  "Name 3 items found in a sewing room",
  "Name 3 types of geometric shapes with 4 sides",
  "Name 3 famous writers of mystery novels",
  "Name 3 items found in a car's trunk",
  "Name 3 types of reptiles that live in water",
  "Name 3 countries in the Arctic Circle",
  "Name 3 items found in a student's locker",
  "Name 3 types of fruit juices",
  "Name 3 famous world-renowned chefs",
  "Name 3 types of noble gases",
  "Name 3 luxury car brands",
  "Name 3 famous psychologists",
  "Name 3 types of bridge types",
  "Name 3 cities in California",
  "Name 3 brands of bottled water",
  "Name 3 characters from The Office",
  "Name 3 types of volcanic rocks",
  "Name 3 famous world-record holders",
  "Name 3 parts of a flower",
  "Name 3 types of coffee beans",
  "Name 3 countries that border Brazil",
  "Name 3 famous female world leaders",
  "Name 3 characters from Toy Story",
  "Name 3 types of dental tools",
  "Name 3 countries in North Africa",
  "Name 3 brands of designer shoes",
  "Name 3 types of human tissue",
  "Name 3 items found in a chemistry lab",
  "Name 3 types of classical dance",
  "Name 3 countries that start with 'U'",
  "Name 3 famous explorers of the Antarctic",
  "Name 3 types of nuts used in baking",
  "Name 3 items found in a darkroom",
  "Name 3 types of infectious diseases",
  "Name 3 famous bridges in the US",
  "Name 3 items found in a doctor's waiting room",
  "Name 3 types of string instruments",
  "Name 3 countries that start with 'V'",
  "Name 3 items found in a hardware store aisle",
  "Name 3 types of nocturnal birds",
  "Name 3 famous novels by Ernest Hemingway",
  "Name 3 items found in a pilot's cockpit",
  "Name 3 types of digital file extensions",
  "Name 3 countries in the European Union",
  "Name 3 items found in a craft box",
  "Name 3 types of Olympic track events",
  "Name 3 famous jazz musicians",
  "Name 3 items found in a hotel minibar",
  "Name 3 countries that border Russia",
  "Name 3 items found in a gym locker room",
  "Name 3 types of weather measuring tools",
  "Name 3 famous astronauts",
  "Name 3 items found in a jewelry workshop",
  "Name 3 types of flightless insects",
  "Name 3 countries that start with 'Y'",
  "Name 3 items found in a basement storage",
  "Name 3 types of deep-sea fish",
  "Name 3 famous movie musicals",
  "Name 3 items found in a theater backstage",
  "Name 3 types of architectural columns",
  "Name 3 countries in the United Kingdom",
  "Name 3 items found in a bakery display",
  "Name 3 types of non-venomous snakes",
  "Name 3 famous sitcom families",
  "Name 3 items found in a bicycle repair kit",
  "Name 3 types of cold-weather fruits",
  "Name 3 countries that start with 'O'",
  "Name 3 items found in a school cafeteria",
  "Name 3 types of heavy machinery",
  "Name 3 famous characters from Greek myths",
  "Name 3 types of computer viruses",
  "Name 3 countries that border the Indian Ocean",
  "Name 3 items found in a fashion designer's studio",
  "Name 3 types of deciduous trees",
  "Name 3 famous albums by Michael Jackson",
  "Name 3 items found in a campsite cooler",
  "Name 3 types of tropical storms",
  "Name 3 countries that start with 'W'",
  "Name 3 items found in a makeup vanity",
  "Name 3 types of urban transport",
  "Name 3 famous landmarks in Italy",
  "Name 3 items found in a laundry basket",
  "Name 3 types of carnivorous animals",
  "Name 3 countries in West Asia",
  "Name 3 items found in a professional kitchen",
  "Name 3 types of sourdough bread",
  "Name 3 famous female athletes",
  "Name 3 items found in a home office",
  "Name 3 countries that start with 'F'",
  "Name 3 items found in a nursery",
  "Name 3 types of marine plants",
  "Name 3 famous movie quotes",
  "Name 3 items found in a picnic basket",
  "Name 3 types of artisan cheeses",
  "Name 3 countries that border Mexico",
  "Name 3 types of light bulbs",
  "Name 3 famous scientists from history",
  "Name 3 items found in a school bus",
  "Name 3 items found in a post office box",
  "Name 3 types of electronic music",
  "Name 3 famous buildings in Paris",
  "Name 3 items found in a coffee bar",
  "Name 3 types of green vegetables",
  "Name 3 countries that start with 'J'",
  "Name 3 items found in a child's toy box",
  "Name 3 types of mountain ranges",
  "Name 3 famous poets from the UK",
  "Name 3 items found in a library's reference section",
  "Name 3 types of predatory birds",
  "Name 3 countries that border Germany",
  "Name 3 types of ball sports",
  "Name 3 famous paintings in the Louvre",
  "Name 3 items found in a survival kit",
  "Name 3 types of kitchen knives",
  "Name 3 types of scientific theories",
  "Name 3 famous people named William",
  "Name 3 types of fabric patterns",
  "Name 3 items found on a construction site",
  "Name 3 types of ancient weapons",
  "Name 3 types of insects with stingers",
  "Name 3 countries that start with 'Q'",
  "Name 3 types of fruit that are yellow",
  "Name 3 famous films from the 1990s",
  "Name 3 types of household pets",
  "Name 3 countries that border China",
  "Name 3 types of sea life with tentacles",
  "Name 3 famous books by Stephen King",
  "Name 3 countries that start with 'Z'",
  "Name 3 types of lizard species",
  "Name 3 famous bands from the 70s",
  "Name 3 types of breakfast foods",
  "Name 3 items found in a pharmacy aisle",
  "Name 3 famous leaders from the 20th century",
  "Name 3 types of Olympic martial arts",
  "Name 3 ingredients in a traditional Pesto",
  "Name 3 countries that border Thailand",
  "Name 3 types of classical architectural orders",
  "Name 3 characters from the Marvel Cinematic Universe",
  "Name 3 methods of heat transfer",
  "Name 3 types of cryptographic algorithms",
  "Name 3 famous landmarks in Australia",
  "Name 3 types of specialized surgical tools",
  "Name 3 countries in the G7",
  "Name 3 types of sushi grade fish",
  "Name 3 historical figures on US bank notes",
  "Name 3 types of poetic meter",
  "Name 3 brands of high-end watches",
  "Name 3 organs in the endocrine system",
  "Name 3 types of legal defenses",
  "Name 3 winners of the Tour de France",
  "Name 3 types of igneous rocks",
  "Name 3 characters from Game of Thrones",
  "Name 3 types of musical intervals",
  "Name 3 countries in the Arabian Peninsula",
  "Name 3 famous world-renowned architects",
  "Name 3 types of atmospheric pressure systems",
  "Name 3 items found in a pilot's flight bag",
  "Name 3 types of coffee brewing methods",
  "Name 3 countries that border the Black Sea",
  "Name 3 famous female authors of the 19th century",
  "Name 3 types of cyber security threats",
  "Name 3 items found in an archery kit",
  "Name 3 types of financial market indices",
  "Name 3 countries in the Baltic region",
  "Name 3 types of non-Newtonian fluids",
  "Name 3 famous space telescopes",
  "Name 3 items found in a carpenter's belt",
  "Name 3 types of cognitive biases",
  "Name 3 countries that border Egypt",
  "Name 3 famous silent film actors",
  "Name 3 types of statistical distributions",
  "Name 3 items found in a chemistry distillation setup",
  "Name 3 types of government structures",
  "Name 3 countries in the Himalayan mountain range",
  "Name 3 types of bridge load stresses",
  "Name 3 famous mathematicians from history",
  "Name 3 items found in a watchmaker's toolkit",
  "Name 3 types of specialized camera lenses",
  "Name 3 countries that border Vietnam",
  "Name 3 famous philosophers of the Enlightenment",
  "Name 3 types of soil horizons",
  "Name 3 items found in a geologist's field bag",
  "Name 3 types of musical time signatures",
  "Name 3 countries in Central Asia",
  "Name 3 types of chemical reaction catalysts",
  "Name 3 famous landmarks in South America",
  "Name 3 items found in a sailing boat's cabin",
  "Name 3 types of structural engineering materials",
  "Name 3 countries that border South Africa",
  "Name 3 famous Impressionist painters",
  "Name 3 types of psychological defense mechanisms",
  "Name 3 items found in a locksmith's kit",
  "Name 3 types of aerodynamic forces",
  "Name 3 countries in Western Europe",
  "Name 3 types of binary logic gates",
  "Name 3 famous historical documents",
  "Name 3 items found in a darkroom for film",
  "Name 3 types of genetic mutations",
  "Name 3 countries that border Turkey",
  "Name 3 famous Surrealist artists",
  "Name 3 types of computer network topologies",
  "Name 3 items found in a tailor's shop",
  "Name 3 types of historical sailing ships",
  "Name 3 countries in the Sahara Desert region",
  "Name 3 types of ancient Greek columns",
  "Name 3 famous female mathematicians",
  "Name 3 items found in a barista's station",
  "Name 3 types of economic theories",
  "Name 3 countries that border Peru",
  "Name 3 famous classical violinists",
  "Name 3 types of cloud storage providers",
  "Name 3 items found in a mechanic's pit",
  "Name 3 types of astronomical nebulae",
  "Name 3 countries in Northern Europe",
  "Name 3 types of biological biomes",
  "Name 3 famous world-renowned physicists",
  "Name 3 items found in a veterinarian's clinic",
  "Name 3 types of mathematical constants",
  "Name 3 countries that border Poland",
  "Name 3 famous Renaissance sculptors",
  "Name 3 types of social influence (psychology)",
  "Name 3 items found in a stage lighting rig",
  "Name 3 types of subatomic particles",
  "Name 3 countries in the Amazon Basin",
  "Name 3 types of volcanic mountains",
  "Name 3 famous jazz saxophonists",
  "Name 3 items found in a printmaking studio",
  "Name 3 types of programming paradigms",
  "Name 3 countries that border Iran",
  "Name 3 famous explorers of the interior of Africa",
  "Name 3 types of tectonic plate boundaries",
  "Name 3 items found in an apothecary",
  "Name 3 types of specialized cheeses from Spain",
  "Name 3 countries in the South Pacific",
  "Name 3 types of legal contracts",
  "Name 3 famous modern architects",
  "Name 3 items found in a baker's proofer",
  "Name 3 types of logic puzzles",
  "Name 3 countries that border Argentina",
  "Name 3 famous operatic tenors",
  "Name 3 types of digital marketing strategies",
  "Name 3 items found in a distillery",
  "Name 3 types of cloud computing models",
  "Name 3 countries in the Horn of Africa",
  "Name 3 types of structural load",
  "Name 3 famous female scientists of the 20th century",
  "Name 3 items found in a goldsmith's bench",
  "Name 3 types of cryptography",
  "Name 3 countries that border Ukraine",
  "Name 3 famous Russian novelists",
  "Name 3 types of astronomical coordinate systems",
  "Name 3 items found in a dental hygiene kit",
  "Name 3 types of psychological disorders",
  "Name 3 types of engineering software",
  "Name 3 famous world heritage sites in India",
  "Name 3 items found in a flight attendant's galley",
  "Name 3 types of specialized fishing lures",
  "Name 3 countries that border Greece",
  "Name 3 famous American transcendentalist writers",
  "Name 3 types of sound waves",
  "Name 3 items found in a pool hall",
  "Name 3 types of scientific classification (Taxonomy)",
  "Name 3 countries in the Caucasus region",
  "Name 3 types of specialized bridge joints",
  "Name 3 famous polymaths",
  "Name 3 items found in a violin maker's workshop",
  "Name 3 types of chemical isotopes",
  "Name 3 countries that border Nigeria",
  "Name 3 famous composers of the Baroque period",
  "Name 3 types of architectural floor plans",
  "Name 3 items found in a film director's monitor bag",
  "Name 3 types of biological kingdoms",
  "Name 3 countries in the Andes mountains",
  "Name 3 types of mathematical proofs",
  "Name 3 famous world leaders of the 19th century",
  "Name 3 items found in a blacksmith's forge",
  "Name 3 types of celestial bodies",
  "Name 3 countries that border Pakistan",
  "Name 3 famous philosophers from Asia",
  "Name 3 types of human muscle tissue",
  "Name 3 items found in a gardener's tool belt",
  "Name 3 types of wind turbines",
  "Name 3 countries in the Nile River basin",
  "Name 3 types of chemical solutions",
  "Name 3 famous world monuments in Egypt",
  "Name 3 items found in a sommelier's kit",
  "Name 3 types of specialized drill bits",
  "Name 3 countries that border Ethiopia",
  "Name 3 famous Japanese directors",
  "Name 3 types of economic indicators",
  "Name 3 items found in a data center",
  "Name 3 types of particle accelerators",
  "Name 3 types of specialized surgical sutures",
  "Name 3 famous world explorers of the 20th century",
  "Name 3 items found in a sound recording studio",
  "Name 3 types of computer memory",
  "Name 3 countries that border Spain",
  "Name 3 famous abstract expressionist painters",
  "Name 3 types of astronomical orbits",
  "Name 3 items found in a high-end restaurant cellar",
  "Name 3 types of social media algorithms",
  "Name 3 countries in the Amazon rainforest",
  "Name 3 types of botanical gardens",
  "Name 3 famous world-renowned sculptors",
  "Name 3 items found in an airplane's cockpit console",
  "Name 3 types of specialized research microscopes",
  "Name 3 countries that border Switzerland",
  "Name 3 famous world explorers of the 15th century",
  "Name 3 types of ocean currents",
  "Name 3 items found in a master chef's pantry",
  "Name 3 types of financial derivatives",
  "Name 3 countries in the Mediterranean region",
  "Name 3 types of specialized medical imaging",
  "Name 3 famous world leaders of the 21st century",
  "Name 3 items found in a professional artist's studio",
  "Name 3 types of specialized software for design",
  "Name 3 famous world thinkers of the 20th century",
  "Name 3 types of specialized global climate zones",
  "Name 3 items found in a high-tech research facility",
  "Name 3 types of specialized biological research tools",
  "Name 3 countries in the Scandinavian region",
  "Name 3 types of specialized engineering projects",
  "Name 3 famous world explorers of the 19th century",
  "Name 3 items found in a professional filmmaker's kit",
  "Name 3 types of specialized computer hardware",
  "Name 3 countries that border Italy",
  "Name 3 famous world thinkers of the 19th century",
  "Name 3 types of specialized global weather events"
];
