export interface Prompt {
  id: number;
  question: string;
}

export const fiveSecondPrompts: Prompt[] = [
  { id: 1, question: "Name 3 countries in Europe" },
  { id: 2, question: "Name 3 fruits that are red" },
  { id: 3, question: "Name 3 movies with Tom Hanks" },
  { id: 4, question: "Name 3 things you find in a kitchen" },
  { id: 5, question: "Name 3 animals that can fly" },
  { id: 6, question: "Name 3 Disney characters" },
  { id: 7, question: "Name 3 famous singers" },
  { id: 8, question: "Name 3 sports played with a ball" },
  { id: 9, question: "Name 3 colors in a rainbow" },
  { id: 10, question: "Name 3 vegetables you eat raw" },
  { id: 11, question: "Name 3 superheroes" },
  { id: 12, question: "Name 3 things in your bathroom" },
  { id: 13, question: "Name 3 types of pasta" },
  { id: 14, question: "Name 3 fast food chains" },
  { id: 15, question: "Name 3 movies from the 1990s" },
  { id: 16, question: "Name 3 famous painters" },
  { id: 17, question: "Name 3 types of birds" },
  { id: 18, question: "Name 3 things you can wear on your head" },
  { id: 19, question: "Name 3 ocean animals" },
  { id: 20, question: "Name 3 holidays in December" },
  { id: 21, question: "Name 3 video games" },
  { id: 22, question: "Name 3 fast vehicles" },
  { id: 23, question: "Name 3 ice cream flavors" },
  { id: 24, question: "Name 3 countries in Asia" },
  { id: 25, question: "Name 3 household appliances" },
  { id: 26, question: "Name 3 famous actors" },
  { id: 27, question: "Name 3 things in a school bag" },
  { id: 28, question: "Name 3 types of flowers" },
  { id: 29, question: "Name 3 things you find at the beach" },
  { id: 30, question: "Name 3 cartoon characters" },
  { id: 31, question: "Name 3 things in a bedroom" },
  { id: 32, question: "Name 3 types of cheese" },
  { id: 33, question: "Name 3 Netflix shows" },
  { id: 34, question: "Name 3 cities in the USA" },
  { id: 35, question: "Name 3 things you can recycle" },
  { id: 36, question: "Name 3 instruments in a band" },
  { id: 37, question: "Name 3 types of trees" },
  { id: 38, question: "Name 3 desserts" },
  { id: 39, question: "Name 3 animals you see at a zoo" },
  { id: 40, question: "Name 3 popular apps" },
  { id: 41, question: "Name 3 things you can drink" },
  { id: 42, question: "Name 3 planets in the solar system" },
  { id: 43, question: "Name 3 superhero movies" },
  { id: 44, question: "Name 3 things you use to write" },
  { id: 45, question: "Name 3 types of sandwiches" },
  { id: 46, question: "Name 3 things in a supermarket" },
  { id: 47, question: "Name 3 TV channels" },
  { id: 48, question: "Name 3 fast food meals" },
  { id: 49, question: "Name 3 famous scientists" },
  { id: 50, question: "Name 3 things you do in the morning" },
  { id: 51, question: "Name 3 famous authors" },
  { id: 52, question: "Name 3 drinks you can order at a cafe" },
  { id: 53, question: "Name 3 countries in Africa" },
  { id: 54, question: "Name 3 types of dogs" },
  { id: 55, question: "Name 3 types of cats" },
  { id: 56, question: "Name 3 popular board games" },
  { id: 57, question: "Name 3 types of pizza toppings" },
  { id: 58, question: "Name 3 things you can find in a park" },
  { id: 59, question: "Name 3 things that are yellow" },
  { id: 60, question: "Name 3 things you can see in the sky" },
  { id: 61, question: "Name 3 types of hats" },
  { id: 62, question: "Name 3 famous YouTubers" },
  { id: 63, question: "Name 3 things you take on vacation" },
  { id: 64, question: "Name 3 sports without a ball" },
  { id: 65, question: "Name 3 Disney movies" },
  { id: 66, question: "Name 3 things you can bake" },
  { id: 67, question: "Name 3 superhero TV shows" },
  { id: 68, question: "Name 3 breakfast foods" },
  { id: 69, question: "Name 3 things you use to clean" },
  { id: 70, question: "Name 3 types of fish" },
  { id: 71, question: "Name 3 things that are soft" },
  { id: 72, question: "Name 3 candies" },
  { id: 73, question: "Name 3 winter clothing items" },
  { id: 74, question: "Name 3 summer activities" },
  { id: 75, question: "Name 3 famous landmarks" },
  { id: 76, question: "Name 3 things in a car" },
  { id: 77, question: "Name 3 things you can smell" },
  { id: 78, question: "Name 3 kinds of shoes" },
  { id: 79, question: "Name 3 things in a grocery store" },
  { id: 80, question: "Name 3 social media platforms" },
  { id: 81, question: "Name 3 musical instruments" },
  { id: 82, question: "Name 3 fast foods you like" },
  { id: 83, question: "Name 3 things you see at night" },
  { id: 84, question: "Name 3 TV shows for kids" },
  { id: 85, question: "Name 3 things you can ride" },
  { id: 86, question: "Name 3 things found in a school" },
  { id: 87, question: "Name 3 flowers" },
  { id: 88, question: "Name 3 board games" },
  { id: 89, question: "Name 3 things in your wallet" },
  { id: 90, question: "Name 3 fruits you peel" },
  { id: 91, question: "Name 3 types of chocolate" },
  { id: 92, question: "Name 3 apps on your phone" },
  { id: 93, question: "Name 3 ocean animals" },
  { id: 94, question: "Name 3 things in a bedroom" },
  { id: 95, question: "Name 3 things in a living room" },
  { id: 96, question: "Name 3 things you do in the morning" },
  { id: 97, question: "Name 3 things you do at night" },
  { id: 98, question: "Name 3 things you can eat with a fork" },
  { id: 99, question: "Name 3 things that are round" },
  { id: 100, question: "Name 3 famous TV commercials" },
  { id: 101, question: "Name 3 things you find in a garage" },
  { id: 102, question: "Name 3 types of pasta sauces" },
  { id: 103, question: "Name 3 things you can write with" },
  { id: 104, question: "Name 3 animals from the jungle" },
  { id: 105, question: "Name 3 ice cream toppings" },
  { id: 106, question: "Name 3 countries in South America" },
  { id: 107, question: "Name 3 breakfast cereals" },
  { id: 108, question: "Name 3 things in a garden" },
  { id: 109, question: "Name 3 board games for adults" },
  { id: 110, question: "Name 3 types of sandwiches" },
  { id: 111, question: "Name 3 things in a fridge" },
  { id: 112, question: "Name 3 famous movie directors" },
  { id: 113, question: "Name 3 types of nuts" },
  { id: 114, question: "Name 3 things in a classroom" },
  { id: 115, question: "Name 3 types of clouds" },
  { id: 116, question: "Name 3 carnival rides" },
  { id: 117, question: "Name 3 famous authors" },
  { id: 118, question: "Name 3 fast animals" },
  { id: 119, question: "Name 3 drinks you can order at a bar" },
  { id: 120, question: "Name 3 things that are green" },
  { id: 121, question: "Name 3 things in a movie theater" },
  { id: 122, question: "Name 3 hobbies" },
  { id: 123, question: "Name 3 sports played indoors" },
  { id: 124, question: "Name 3 breakfast foods with eggs" },
  { id: 125, question: "Name 3 things you see at a wedding" },
  { id: 126, question: "Name 3 types of candy bars" },
  { id: 127, question: "Name 3 items in a toolbox" },
  { id: 128, question: "Name 3 pets other than cats and dogs" },
  { id: 129, question: "Name 3 types of pizza" },
  { id: 130, question: "Name 3 famous inventors" },
  { id: 131, question: "Name 3 countries in North America" },
  { id: 132, question: "Name 3 things in a hospital" },
  { id: 133, question: "Name 3 social media apps" },
  { id: 134, question: "Name 3 things that are red" },
  { id: 135, question: "Name 3 types of trees" },
  { id: 136, question: "Name 3 superheroes from Marvel" },
  { id: 137, question: "Name 3 things in a bathroom" },
  { id: 138, question: "Name 3 TV shows for adults" },
  { id: 139, question: "Name 3 things you can find at a carnival" },
  { id: 140, question: "Name 3 video game consoles" },
  { id: 141, question: "Name 3 snacks you eat at the movies" },
  { id: 142, question: "Name 3 types of hats" },
  { id: 143, question: "Name 3 board games for kids" },
  { id: 144, question: "Name 3 things you can carry in a backpack" },
  { id: 145, question: "Name 3 types of shoes" },
  { id: 146, question: "Name 3 countries with beaches" },
  { id: 147, question: "Name 3 movies about superheroes" },
  { id: 148, question: "Name 3 things that are yellow" },
  { id: 149, question: "Name 3 things you can eat for lunch" },
  { id: 150, question: "Name 3 animals from the desert" },
  { id: 151, question: "Name 3 things you find in a kitchen drawer" },
  { id: 152, question: "Name 3 types of fruit juices" },
  { id: 153, question: "Name 3 animals that live in water" },
  { id: 154, question: "Name 3 musical instruments in an orchestra" },
  { id: 155, question: "Name 3 things you see in a park" },
  { id: 156, question: "Name 3 fast food desserts" },
  { id: 157, question: "Name 3 countries in Europe starting with B" },
  { id: 158, question: "Name 3 things you use to clean your teeth" },
  { id: 159, question: "Name 3 famous TV series from the 2000s" },
  { id: 160, question: "Name 3 things in a hotel room" },
  { id: 161, question: "Name 3 popular YouTube channels" },
  { id: 162, question: "Name 3 types of pasta shapes" },
  { id: 163, question: "Name 3 fast animals in the world" },
  { id: 164, question: "Name 3 things you can cook on a grill" },
  { id: 165, question: "Name 3 types of cars" },
  { id: 166, question: "Name 3 board games for 2 players" },
  { id: 167, question: "Name 3 things in a school classroom" },
  { id: 168, question: "Name 3 types of sandwiches you like" },
  { id: 169, question: "Name 3 things you can buy at a bakery" },
  { id: 170, question: "Name 3 animals that live in the jungle" },
  { id: 171, question: "Name 3 video games from the 1990s" },
  { id: 172, question: "Name 3 things in a bedroom" },
  { id: 173, question: "Name 3 types of desserts" },
  { id: 174, question: "Name 3 famous painters" },
  { id: 175, question: "Name 3 sports played with a ball" },
  { id: 176, question: "Name 3 types of clothing you wear in winter" },
  { id: 177, question: "Name 3 things you find in a supermarket" },
  { id: 178, question: "Name 3 types of flowers" },
  { id: 179, question: "Name 3 fast foods you like" },
  { id: 180, question: "Name 3 things you can eat for breakfast" },
  { id: 181, question: "Name 3 things you can see in the sky" },
  { id: 182, question: "Name 3 animals you can see at a zoo" },
  { id: 183, question: "Name 3 Disney movies" },
  { id: 184, question: "Name 3 types of hats" },
  { id: 185, question: "Name 3 breakfast cereals" },
  { id: 186, question: "Name 3 countries in Asia" },
  { id: 187, question: "Name 3 types of pizza toppings" },
  { id: 188, question: "Name 3 things you use to write" },
  { id: 189, question: "Name 3 superheroes from DC Comics" },
  { id: 190, question: "Name 3 video games you like" },
  { id: 191, question: "Name 3 types of fish" },
  { id: 192, question: "Name 3 things you take on vacation" },
  { id: 193, question: "Name 3 board games for adults" },
  { id: 194, question: "Name 3 types of vegetables" },
  { id: 195, question: "Name 3 things you see at the beach" },
  { id: 196, question: "Name 3 famous singers" },
  { id: 197, question: "Name 3 types of chocolate" },
  { id: 198, question: "Name 3 drinks you can order at a café" },
  { id: 199, question: "Name 3 types of shoes" },
  { id: 200, question: "Name 3 things in a backpack" },
  { id: 201, question: "Name 3 types of trees" },
  { id: 202, question: "Name 3 things you can eat with your hands" },
  { id: 203, question: "Name 3 famous landmarks in Europe" },
  { id: 204, question: "Name 3 things you find in a car" },
  { id: 205, question: "Name 3 TV shows for adults" },
  { id: 206, question: "Name 3 types of pets" },
  { id: 207, question: "Name 3 things in a classroom" },
  { id: 208, question: "Name 3 musical instruments" },
  { id: 209, question: "Name 3 winter sports" },
  { id: 210, question: "Name 3 things you can wear on your feet" },
  { id: 211, question: "Name 3 animals from the desert" },
  { id: 212, question: "Name 3 Disney characters" },
  { id: 213, question: "Name 3 types of pasta" },
  { id: 214, question: "Name 3 breakfast foods" },
  { id: 215, question: "Name 3 things you find in a kitchen" },
  { id: 216, question: "Name 3 types of sandwiches" },
  { id: 217, question: "Name 3 famous actors" },
  { id: 218, question: "Name 3 things you find at a park" },
  { id: 219, question: "Name 3 sports played outdoors" },
  { id: 220, question: "Name 3 types of flowers" },
  { id: 221, question: "Name 3 candies" },
  { id: 222, question: "Name 3 things in a bedroom" },
  { id: 223, question: "Name 3 ice cream flavors" },
  { id: 224, question: "Name 3 things in a supermarket" },
  { id: 225, question: "Name 3 types of drinks" },
  { id: 226, question: "Name 3 countries in Africa" },
  { id: 227, question: "Name 3 popular apps" },
  { id: 228, question: "Name 3 things you do in the morning" },
  { id: 229, question: "Name 3 animals you see at a zoo" },
  { id: 230, question: "Name 3 breakfast cereals" },
  { id: 231, question: "Name 3 types of pizza toppings" },
  { id: 232, question: "Name 3 things you can recycle" },
  { id: 233, question: "Name 3 things in your bathroom" },
  { id: 234, question: "Name 3 famous painters" },
  { id: 235, question: "Name 3 movies from the 1990s" },
  { id: 236, question: "Name 3 superheroes" },
  { id: 237, question: "Name 3 things in a garage" },
  { id: 238, question: "Name 3 types of shoes" },
  { id: 239, question: "Name 3 social media platforms" },
  { id: 240, question: "Name 3 things you can bake" },
  { id: 241, question: "Name 3 board games" },
  { id: 242, question: "Name 3 things in a school bag" },
  { id: 243, question: "Name 3 types of cats" },
  { id: 244, question: "Name 3 things you can smell" },
  { id: 245, question: "Name 3 fast foods you like" },
  { id: 246, question: "Name 3 things in a living room" },
  { id: 247, question: "Name 3 countries in North America" },
  { id: 248, question: "Name 3 things in a hotel room" },
  { id: 249, question: "Name 3 things you can eat for lunch" },
  { id: 250, question: "Name 3 animals that can fly" }
];
