export interface Prompt {
  id: number;
  question: string;
}

export const fiveSecondPrompts: Prompt[] = [
  {"id": 1, "question": "Name 3 countries in Asia" },
  { "id": 2, "question": "Name 3 elements on the Periodic Table" },
  { "id": 3, "question": "Name 3 US Presidents" },
  { "id": 4, "question": "Name 3 planets in our solar system" },
  { "id": 5, "question": "Name 3 characters from Harry Potter" },
  { "id": 6, "question": "Name 3 brands of soda" },
  { "id": 7, "question": "Name 3 European capital cities" },
  { "id": 8, "question": "Name 3 types of pasta" },
  { "id": 9, "question": "Name 3 sports that use a ball" },
  { "id": 10, "question": "Name 3 colors in the rainbow" },
  { "id": 11, "question": "Name 3 breeds of dogs" },
  { "id": 12, "question": "Name 3 African countries" },
  { "id": 13, "question": "Name 3 primary colors" },
  { "id": 14, "question": "Name 3 Marvel superheroes" },
  { "id": 15, "question": "Name 3 famous painters" },
  { "id": 16, "question": "Name 3 types of fruit that are red" },
  { "id": 17, "question": "Name 3 bones in the human body" },
  { "id": 18, "question": "Name 3 musical instruments" },
  { "id": 19, "question": "Name 3 languages spoken in Europe" },
  { "id": 20, "question": "Name 3 ocean animals" },
  { "id": 21, "question": "Name 3 internal organs" },
  { "id": 22, "question": "Name 3 Disney movies" },
  { "id": 23, "question": "Name 3 types of cheese" },
  { "id": 24, "question": "Name 3 historical wars" },
  { "id": 25, "question": "Name 3 Greek Gods" },
  { "id": 26, "question": "Name 3 fast food chains" },
  { "id": 27, "question": "Name 3 car manufacturers" },
  { "id": 28, "question": "Name 3 layers of the Earth" },
  { "id": 29, "question": "Name 3 Taylor Swift songs" },
  { "id": 30, "question": "Name 3 items found in a bathroom" },
  { "id": 31, "question": "Name 3 units of measurement" },
  { "id": 32, "question": "Name 3 continents" },
  { "id": 33, "question": "Name 3 things that fly" },
  { "id": 34, "question": "Name 3 types of flowers" },
  { "id": 35, "question": "Name 3 social media apps" },
  { "id": 36, "question": "Name 3 countries that start with 'S'" },
  { "id": 37, "question": "Name 3 mammals that live in water" },
  { "id": 38, "question": "Name 3 pieces of furniture" },
  { "id": 39, "question": "Name 3 board games" },
  { "id": 40, "question": "Name 3 constellations" },
  { "id": 41, "question": "Name 3 types of triangles" },
  { "id": 42, "question": "Name 3 James Bond actors" },
  { "id": 43, "question": "Name 3 parts of a plant" },
  { "id": 44, "question": "Name 3 famous world landmarks" },
  { "id": 45, "question": "Name 3 ingredients in a cake" },
  { "id": 46, "question": "Name 3 genres of music" },
  { "id": 47, "question": "Name 3 luxury fashion brands" },
  { "id": 48, "question": "Name 3 flightless birds" },
  { "id": 49, "question": "Name 3 items in a toolbox" },
  { "id": 50, "question": "Name 3 video game consoles" },
  { "id": 51, "question": "Name 3 countries with 'New' in their name" },
  { "id": 52, "question": "Name 3 Nobel Prize winners" },
  { "id": 53, "question": "Name 3 types of clouds" },
  { "id": 54, "question": "Name 3 songs by The Beatles" },
  { "id": 55, "question": "Name 3 Olympic sports" },
  { "id": 56, "question": "Name 3 items found in a wallet" },
  { "id": 57, "question": "Name 3 types of tea" },
  { "id": 58, "question": "Name 3 desert animals" },
  { "id": 59, "question": "Name 3 US States on the East Coast" },
  { "id": 60, "question": "Name 3 kitchen appliances" },
  { "id": 61, "question": "Name 3 Shakespeare plays" },
  { "id": 62, "question": "Name 3 characters from Star Wars" },
  { "id": 63, "question": "Name 3 types of snakes" },
  { "id": 64, "question": "Name 3 prime numbers" },
  { "id": 65, "question": "Name 3 famous inventors" },
  { "id": 66, "question": "Name 3 things made of glass" },
  { "id": 67, "question": "Name 3 words that rhyme with 'Blue'" },
  { "id": 68, "question": "Name 3 types of weather" },
  { "id": 69, "question": "Name 3 mountain ranges" },
  { "id": 70, "question": "Name 3 Netflix original series" },
  { "id": 71, "question": "Name 3 parts of a cell" },
  { "id": 72, "question": "Name 3 movies starring Tom Hanks" },
  { "id": 73, "question": "Name 3 ways to cook an egg" },
  { "id": 74, "question": "Name 3 capital cities in South America" },
  { "id": 75, "question": "Name 3 things that are yellow" },
  { "id": 76, "question": "Name 3 species of sharks" },
  { "id": 77, "question": "Name 3 famous scientists" },
  { "id": 78, "question": "Name 3 punctuation marks" },
  { "id": 79, "question": "Name 3 types of berries" },
  { "id": 80, "question": "Name 3 countries in the Middle East" },
  { "id": 81, "question": "Name 3 actors named 'Chris'" },
  { "id": 82, "question": "Name 3 types of weather disasters" },
  { "id": 83, "question": "Name 3 things you find at a beach" },
  { "id": 84, "question": "Name 3 ingredients in a salad" },
  { "id": 85, "question": "Name 3 world currencies" },
  { "id": 86, "question": "Name 3 parts of a computer" },
  { "id": 87, "question": "Name 3 things that are sticky" },
  { "id": 88, "question": "Name 3 Pixar movies" },
  { "id": 89, "question": "Name 3 types of whales" },
  { "id": 90, "question": "Name 3 rivers in Europe" },
  { "id": 91, "question": "Name 3 sitcoms from the 90s" },
  { "id": 92, "question": "Name 3 historical empires" },
  { "id": 93, "question": "Name 3 items of winter clothing" },
  { "id": 94, "question": "Name 3 things that smell good" },
  { "id": 95, "question": "Name 3 states in Australia" },
  { "id": 96, "question": "Name 3 hobbies" },
  { "id": 97, "question": "Name 3 flavors of ice cream" },
  { "id": 98, "question": "Name 3 types of trees" },
  { "id": 99, "question": "Name 3 breakfast cereals" },
  { "id": 100, "question": "Name 3 world-famous bridges" },
  { "id": 101, "question": "Name 3 items in a first aid kit" },
  { "id": 102, "question": "Name 3 female singers" },
  { "id": 103, "question": "Name 3 things that are sharp" },
  { "id": 104, "question": "Name 3 types of rocks" },
  { "id": 105, "question": "Name 3 Japanese cities" },
  { "id": 106, "question": "Name 3 things you do at the gym" },
  { "id": 107, "question": "Name 3 characters from Friends" },
  { "id": 108, "question": "Name 3 colors on the Italian flag" },
  { "id": 109, "question": "Name 3 items in a school bag" },
  { "id": 110, "question": "Name 3 programming languages" },
  { "id": 111, "question": "Name 3 countries bordering Germany" },
  { "id": 112, "question": "Name 3 types of shoes" },
  { "id": 113, "question": "Name 3 DC superheroes" },
  { "id": 114, "question": "Name 3 elements that are metals" },
  { "id": 115, "question": "Name 3 ways to say 'Hello'" },
  { "id": 116, "question": "Name 3 things you find in a library" },
  { "id": 117, "question": "Name 3 movie directors" },
  { "id": 118, "question": "Name 3 types of soup" },
  { "id": 119, "question": "Name 3 countries in North America" },
  { "id": 120, "question": "Name 3 things made of wood" },
  { "id": 121, "question": "Name 3 emergency services" },
  { "id": 122, "question": "Name 3 components of a burger" },
  { "id": 123, "question": "Name 3 famous poets" },
  { "id": 124, "question": "Name 3 types of bread" },
  { "id": 125, "question": "Name 3 things you see in the sky at night" },
  { "id": 126, "question": "Name 3 animals with trunks or tusks" },
  { "id": 127, "question": "Name 3 cities in Canada" },
  { "id": 128, "question": "Name 3 types of nuts" },
  { "id": 129, "question": "Name 3 Harry Potter houses" },
  { "id": 130, "question": "Name 3 things that are cold" },
  { "id": 131, "question": "Name 3 types of dance" },
  { "id": 132, "question": "Name 3 US state capitals" },
  { "id": 133, "question": "Name 3 things that are spicy" },
  { "id": 134, "question": "Name 3 breeds of cats" },
  { "id": 135, "question": "Name 3 types of fabric" },
  { "id": 136, "question": "Name 3 countries in Central America" },
  { "id": 137, "question": "Name 3 items in a makeup bag" },
  { "id": 138, "question": "Name 3 things you find in a garage" },
  { "id": 139, "question": "Name 3 rappers" },
  { "id": 140, "question": "Name 3 pieces of jewelry" },
  { "id": 141, "question": "Name 3 things you find in a park" },
  { "id": 142, "question": "Name 3 types of bears" },
  { "id": 143, "question": "Name 3 countries that start with 'B'" },
  { "id": 144, "question": "Name 3 classic horror movies" },
  { "id": 145, "question": "Name 3 things you find in a laundry room" },
  { "id": 146, "question": "Name 3 types of wind instruments" },
  { "id": 147, "question": "Name 3 European rivers" },
  { "id": 148, "question": "Name 3 things that produce heat" },
  { "id": 149, "question": "Name 3 movie franchises" },
  { "id": 150, "question": "Name 3 items on a breakfast menu" },
  { "id": 151, "question": "Name 3 things made of plastic" },
  { "id": 152, "question": "Name 3 cities in England" },
  { "id": 153, "question": "Name 3 types of monkeys" },
  { "id": 154, "question": "Name 3 characters from The Avengers" },
  { "id": 155, "question": "Name 3 things you see at a wedding" },
  { "id": 156, "question": "Name 3 types of wine" },
  { "id": 157, "question": "Name 3 brands of computers" },
  { "id": 158, "question": "Name 3 countries in Scandinavia" },
  { "id": 159, "question": "Name 3 items found in a toolbox" },
  { "id": 160, "question": "Name 3 types of dinosaurs" },
  { "id": 161, "question": "Name 3 things you find in an office" },
  { "id": 162, "question": "Name 3 types of pasta shapes" },
  { "id": 163, "question": "Name 3 famous queens" },
  { "id": 164, "question": "Name 3 things you find in a purse" },
  { "id": 165, "question": "Name 3 flavors of potato chips" },
  { "id": 166, "question": "Name 3 US states that start with 'A'" },
  { "id": 167, "question": "Name 3 things you do at a party" },
  { "id": 168, "question": "Name 3 species of birds" },
  { "id": 169, "question": "Name 3 things found in a nursery" },
  { "id": 170, "question": "Name 3 types of fruit that have pits" },
  { "id": 171, "question": "Name 3 things that are loud" },
  { "id": 172, "question": "Name 3 brands of sneakers" },
  { "id": 173, "question": "Name 3 countries that use the Euro" },
  { "id": 174, "question": "Name 3 pieces of playground equipment" },
  { "id": 175, "question": "Name 3 types of candy bars" },
  { "id": 176, "question": "Name 3 characters from Disney's Lion King" },
  { "id": 177, "question": "Name 3 things you find in a doctor's office" },
  { "id": 178, "question": "Name 3 types of transportation" },
  { "id": 179, "question": "Name 3 cities in Florida" },
  { "id": 180, "question": "Name 3 things made of metal" },
  { "id": 181, "question": "Name 3 types of lizards" },
  { "id": 182, "question": "Name 3 brands of watch" },
  { "id": 183, "question": "Name 3 things you find in a hotel room" },
  { "id": 184, "question": "Name 3 famous explorers" },
  { "id": 185, "question": "Name 3 types of cereal" },
  { "id": 186, "question": "Name 3 things you find at a zoo" },
  { "id": 187, "question": "Name 3 words that rhyme with 'Cat'" },
  { "id": 188, "question": "Name 3 things that are green" },
  { "id": 189, "question": "Name 3 parts of a car" },
  { "id": 190, "question": "Name 3 types of insects" },
  { "id": 191, "question": "Name 3 things you find on a farm" },
  { "id": 192, "question": "Name 3 countries in South America" },
  { "id": 193, "question": "Name 3 types of furniture in a bedroom" },
  { "id": 194, "question": "Name 3 ingredients in a sandwich" },
  { "id": 195, "question": "Name 3 things that are heavy" },
  { "id": 196, "question": "Name 3 types of fish" },
  { "id": 197, "question": "Name 3 things you find in a classroom" },
  { "id": 198, "question": "Name 3 brands of chocolate" },
  { "id": 199, "question": "Name 3 things you see at a circus" },
  { "id": 200, "question": "Name 3 types of rodents" },
  { "id": 201, "question": "Name 3 scientists who won a Nobel Prize" },
  { "id": 202, "question": "Name 3 components of an atom" },
  { "id": 203, "question": "Name 3 organs in the respiratory system" },
  { "id": 204, "question": "Name 3 phases of the moon" },
  { "id": 205, "question": "Name 3 types of electromagnetic radiation" },
  { "id": 206, "question": "Name 3 famous explorers of the sea" },
  { "id": 207, "question": "Name 3 ancient civilizations" },
  { "id": 208, "question": "Name 3 types of simple machines" },
  { "id": 209, "question": "Name 3 female authors" },
  { "id": 210, "question": "Name 3 plays written by Shakespeare" },
  { "id": 211, "question": "Name 3 Greek philosophers" },
  { "id": 212, "question": "Name 3 countries that were part of the Roman Empire" },
  { "id": 213, "question": "Name 3 famous nurses or doctors from history" },
  { "id": 214, "question": "Name 3 types of poetic devices" },
  { "id": 215, "question": "Name 3 books by Stephen King" },
  { "id": 216, "question": "Name 3 Roman numerals" },
  { "id": 217, "question": "Name 3 types of bridge structures" },
  { "id": 218, "question": "Name 3 famous classical composers" },
  { "id": 219, "question": "Name 3 tools used by a carpenter" },
  { "id": 220, "question": "Name 3 things you do at an airport" },
  { "id": 221, "question": "Name 3 types of martial arts" },
  { "id": 222, "question": "Name 3 items used in a science lab" },
  { "id": 223, "question": "Name 3 things that are waterproof" },
  { "id": 224, "question": "Name 3 types of fuel" },
  { "id": 225, "question": "Name 3 things that can be recycled" },
  { "id": 226, "question": "Name 3 parts of a bicycle" },
  { "id": 227, "question": "Name 3 types of percussion instruments" },
  { "id": 228, "question": "Name 3 famous statues" },
  { "id": 229, "question": "Name 3 things you find in a forest" },
  { "id": 230, "question": "Name 3 types of grains" },
  { "id": 231, "question": "Name 3 things that happen during a storm" },
  { "id": 232, "question": "Name 3 Olympic swimming strokes" },
  { "id": 233, "question": "Name 3 things you find in a desert" },
  { "id": 234, "question": "Name 3 types of energy" },
  { "id": 235, "question": "Name 3 things that have wheels" },
  { "id": 236, "question": "Name 3 major world religions" },
  { "id": 237, "question": "Name 3 things you do before going to bed" },
  { "id": 238, "question": "Name 3 types of shellfish" },
  { "id": 239, "question": "Name 3 things you find in a gym locker" },
  { "id": 240, "question": "Name 3 ways to preserve food" },
  { "id": 241, "question": "Name 3 things that grow underground" },
  { "id": 242, "question": "Name 3 types of geometric shapes" },
  { "id": 243, "question": "Name 3 things you find in a sewing kit" },
  { "id": 244, "question": "Name 3 types of non-fiction books" },
  { "id": 245, "question": "Name 3 things that produce a reflection" },
  { "id": 246, "question": "Name 3 types of citrus fruit" },
  { "id": 247, "question": "Name 3 things that can be folded" },
  { "id": 248, "question": "Name 3 types of map projections" },
  { "id": 249, "question": "Name 3 things you find in a movie theater" },
  { "id": 250, "question": "Name 3 types of volcanic eruptions" },
  { "id": 251, "question": "Name 3 things you find in a museum" },
  { "id": 252, "question": "Name 3 types of competitive racing" },
  { "id": 253, "question": "Name 3 things you find on a construction site" },
  { "id": 254, "question": "Name 3 types of natural fibers" },
  { "id": 255, "question": "Name 3 things that are transparent" },
  { "id": 256, "question": "Name 3 types of winter sports" },
  { "id": 257, "question": "Name 3 things you find in a hospital" },
  { "id": 258, "question": "Name 3 types of human teeth" },
  { "id": 259, "question": "Name 3 things you find in a toolbox" },
  { "id": 260, "question": "Name 3 types of broadleaf trees" },
  { "id": 261, "question": "Name 3 things you do on a Sunday" },
  { "id": 262, "question": "Name 3 types of carnivorous plants" },
  { "id": 263, "question": "Name 3 things you find at a bus stop" },
  { "id": 264, "question": "Name 3 types of money (currencies)" },
  { "id": 265, "question": "Name 3 things you find in a garden" },
  { "id": 266, "question": "Name 3 types of spicy food" },
  { "id": 267, "question": "Name 3 things you find in a refrigerator" },
  { "id": 268, "question": "Name 3 types of primates" },
  { "id": 269, "question": "Name 3 things you find in a cave" },
  { "id": 270, "question": "Name 3 types of exercise" },
  { "id": 271, "question": "Name 3 things you find in a drawer" },
  { "id": 272, "question": "Name 3 types of software" },
  { "id": 273, "question": "Name 3 things you find on a dinner table" },
  { "id": 274, "question": "Name 3 types of poetry" },
  { "id": 275, "question": "Name 3 things you find in a backpack" },
  { "id": 276, "question": "Name 3 types of weather patterns" },
  { "id": 277, "question": "Name 3 things you find at a gas station" },
  { "id": 278, "question": "Name 3 types of craft hobbies" },
  { "id": 279, "question": "Name 3 things you find in a purse" },
  { "id": 280, "question": "Name 3 types of baked goods" },
  { "id": 281, "question": "Name 3 things you find in a school" },
  { "id": 282, "question": "Name 3 types of aquatic plants" },
  { "id": 283, "question": "Name 3 things you find in a theater" },
  { "id": 284, "question": "Name 3 types of medical specialists" },
  { "id": 285, "question": "Name 3 things you find in a pharmacy" },
  { "id": 286, "question": "Name 3 types of footwear" },
  { "id": 287, "question": "Name 3 things you find at a carnival" },
  { "id": 288, "question": "Name 3 types of cold-blooded animals" },
  { "id": 289, "question": "Name 3 things you find in a kitchen" },
  { "id": 290, "question": "Name 3 types of reptiles" },
  { "id": 291, "question": "Name 3 things you find in a bedroom" },
  { "id": 292, "question": "Name 3 types of candy" },
  { "id": 293, "question": "Name 3 things you find in a living room" },
  { "id": 294, "question": "Name 3 types of birds" },
  { "id": 295, "question": "Name 3 things you find in a garage" },
  { "id": 296, "question": "Name 3 types of cars" },
  { "id": 297, "question": "Name 3 things you find in a basement" },
  { "id": 298, "question": "Name 3 types of trees" },
  { "id": 299, "question": "Name 3 things you find in an attic" },
  { "id": 300, "question": "Name 3 types of fruit" },
  { "id": 301, "question": "Name 3 types of pasta" },
  { "id": 302, "question": "Name 3 things you find in a grocery store" },
  { "id": 303, "question": "Name 3 types of vegetables" },
  { "id": 304, "question": "Name 3 things you find in a hardware store" },
  { "id": 305, "question": "Name 3 types of meat" },
  { "id": 306, "question": "Name 3 things you find in a toy store" },
  { "id": 307, "question": "Name 3 types of bread" },
  { "id": 308, "question": "Name 3 things you find in a clothing store" },
  { "id": 309, "question": "Name 3 types of jewelry" },
  { "id": 310, "question": "Name 3 things you find in a pet store" },
  { "id": 311, "question": "Name 3 types of animals" },
  { "id": 312, "question": "Name 3 things you find in a bank" },
  { "id": 313, "question": "Name 3 types of fish" },
  { "id": 314, "question": "Name 3 things you find in a post office" },
  { "id": 315, "question": "Name 3 types of flowers" },
  { "id": 316, "question": "Name 3 things you find in a library" },
  { "id": 317, "question": "Name 3 types of music" },
  { "id": 318, "question": "Name 3 things you find in a museum" },
  { "id": 319, "question": "Name 3 types of books" },
  { "id": 320, "question": "Name 3 things you find in a park" },
  { "id": 321, "question": "Name 3 types of games" },
  { "id": 322, "question": "Name 3 things you find in a stadium" },
  { "id": 323, "question": "Name 3 types of sports" },
  { "id": 324, "question": "Name 3 things you find in a swimming pool" },
  { "id": 325, "question": "Name 3 types of art" },
  { "id": 326, "question": "Name 3 things you find in a restaurant" },
  { "id": 327, "question": "Name 3 types of food" },
  { "id": 328, "question": "Name 3 things you find in a cafe" },
  { "id": 329, "question": "Name 3 types of drinks" },
  { "id": 330, "question": "Name 3 things you find in a bar" },
  { "id": 331, "question": "Name 3 types of alcohol" },
  { "id": 332, "question": "Name 3 things you find in a nightclub" },
  { "id": 333, "question": "Name 3 types of people" },
  { "id": 334, "question": "Name 3 things you find in a city" },
  { "id": 335, "question": "Name 3 types of buildings" },
  { "id": 336, "question": "Name 3 things you find in a village" },
  { "id": 337, "question": "Name 3 types of houses" },
  { "id": 338, "question": "Name 3 things you find in the ocean" },
  { "id": 339, "question": "Name 3 types of islands" },
  { "id": 340, "question": "Name 3 things you find on a mountain" },
  { "id": 341, "question": "Name 3 types of mountains" },
  { "id": 342, "question": "Name 3 things you find in a desert" },
  { "id": 343, "question": "Name 3 types of deserts" },
  { "id": 344, "question": "Name 3 things you find in a forest" },
  { "id": 345, "question": "Name 3 types of forests" },
  { "id": 346, "question": "Name 3 things you find in space" },
  { "id": 347, "question": "Name 3 types of stars" },
  { "id": 348, "question": "Name 3 things you find in the sky" },
  { "id": 349, "question": "Name 3 types of clouds" },
  { "id": 350, "question": "Name 3 things you find on the ground" },
  { "id": 351, "question": "Name 3 types of soil" },
  { "id": 352, "question": "Name 3 things you find in water" },
  { "id": 353, "question": "Name 3 types of water" },
  { "id": 354, "question": "Name 3 things you find in air" },
  { "id": 355, "question": "Name 3 types of gases" },
  { "id": 356, "question": "Name 3 things you find in fire" },
  { "id": 357, "question": "Name 3 types of heat" },
  { "id": 358, "question": "Name 3 things you find in light" },
  { "id": 359, "question": "Name 3 types of light" },
  { "id": 360, "question": "Name 3 things you find in sound" },
  { "id": 361, "question": "Name 3 types of sound" },
  { "id": 362, "question": "Name 3 things you find in time" },
  { "id": 363, "question": "Name 3 types of time" },
  { "id": 364, "question": "Name 3 things you find in life" },
  { "id": 365, "question": "Name 3 types of life" },
  { "id": 366, "question": "Name 3 things you find in death" },
  { "id": 367, "question": "Name 3 types of death" },
  { "id": 368, "question": "Name 3 things you find in love" },
  { "id": 369, "question": "Name 3 types of love" },
  { "id": 370, "question": "Name 3 things you find in hate" },
  { "id": 371, "question": "Name 3 types of hate" },
  { "id": 372, "question": "Name 3 things you find in war" },
  { "id": 373, "question": "Name 3 types of war" },
  { "id": 374, "question": "Name 3 things you find in peace" },
  { "id": 375, "question": "Name 3 types of peace" },
  { "id": 376, "question": "Name 3 things you find in a dream" },
  { "id": 377, "question": "Name 3 types of dreams" },
  { "id": 378, "question": "Name 3 things you find in a nightmare" },
  { "id": 379, "question": "Name 3 types of nightmares" },
  { "id": 380, "question": "Name 3 things you find in a thought" },
  { "id": 381, "question": "Name 3 types of thoughts" },
  { "id": 382, "question": "Name 3 things you find in a feeling" },
  { "id": 383, "question": "Name 3 types of feelings" },
  { "id": 384, "question": "Name 3 things you find in a memory" },
  { "id": 385, "question": "Name 3 types of memories" },
  { "id": 286, "question": "Name 3 things you find in a secret" },
  { "id": 387, "question": "Name 3 types of secrets" },
  { "id": 388, "question": "Name 3 things you find in a lie" },
  { "id": 389, "question": "Name 3 types of lies" },
  { "id": 390, "question": "Name 3 things you find in a truth" },
  { "id": 391, "question": "Name 3 types of truth" },
  { "id": 392, "question": "Name 3 things you find in a question" },
  { "id": 393, "question": "Name 3 types of questions" },
  { "id": 394, "question": "Name 3 things you find in an answer" },
  { "id": 395, "question": "Name 3 types of answers" },
  { "id": 396, "question": "Name 3 things you find in a word" },
  { "id": 397, "question": "Name 3 types of words" },
  { "id": 398, "question": "Name 3 things you find in a sentence" },
  { "id": 399, "question": "Name 3 types of sentences" },
  { "id": 400, "question": "Name 3 things you find in a story" },
  { "id": 401, "question": "Name 3 movies starring Leonardo DiCaprio" },
  { "id": 402, "question": "Name 3 types of cloud formations" },
  { "id": 403, "question": "Name 3 characters from The Simpsons" },
  { "id": 404, "question": "Name 3 countries in Oceania" },
  { "id": 405, "question": "Name 3 components of a cell" },
  { "id": 406, "question": "Name 3 80s pop stars" },
  { "id": 407, "question": "Name 3 types of chess pieces" },
  { "id": 408, "question": "Name 3 world-famous sculptures" },
  { "id": 409, "question": "Name 3 parts of the human eye" },
  { "id": 410, "question": "Name 3 winners of the FIFA World Cup" },
  { "id": 411, "question": "Name 3 types of energy sources" },
  { "id": 412, "question": "Name 3 items found in a spaceship" },
  { "id": 413, "question": "Name 3 types of sushi rolls" },
  { "id": 414, "question": "Name 3 songs by Queen" },
  { "id": 415, "question": "Name 3 countries that border France" },
  { "id": 416, "question": "Name 3 layers of the atmosphere" },
  { "id": 417, "question": "Name 3 tools used by a surgeon" },
  { "id": 418, "question": "Name 3 types of sharks" },
  { "id": 419, "question": "Name 3 DC Comics villains" },
  { "id": 420, "question": "Name 3 types of classical music composers" },
  { "id": 421, "question": "Name 3 items found in a sewing kit" },
  { "id": 422, "question": "Name 3 countries in Scandinavia" },
  { "id": 423, "question": "Name 3 types of tea leaves" },
  { "id": 424, "question": "Name 3 famous fashion designers" },
  { "id": 425, "question": "Name 3 types of engineering" },
  { "id": 426, "question": "Name 3 items found at a campsite" },
  { "id": 427, "question": "Name 3 types of non-fiction book genres" },
  { "id": 428, "question": "Name 3 characters from The Lord of the Rings" },
  { "id": 429, "question": "Name 3 types of bridge designs" },
  { "id": 430, "question": "Name 3 famous female scientists" },
  { "id": 431, "question": "Name 3 things you see at a parade" },
  { "id": 432, "question": "Name 3 types of pasta sauces" },
  { "id": 433, "question": "Name 3 countries that start with 'I'" },
  { "id": 434, "question": "Name 3 characters from SpongeBob SquarePants" },
  { "id": 435, "question": "Name 3 items found in a science lab" },
  { "id": 436, "question": "Name 3 types of social media filters" },
  { "id": 437, "question": "Name 3 famous world leaders from the 1900s" },
  { "id": 438, "question": "Name 3 types of exercise equipment" },
  { "id": 439, "question": "Name 3 items found in a toolbox" },
  { "id": 440, "question": "Name 3 types of citrus fruits" },
  { "id": 441, "question": "Name 3 countries in the Caribbean" },
  { "id": 442, "question": "Name 3 types of programming languages" },
  { "id": 443, "question": "Name 3 items found on a desk" },
  { "id": 444, "question": "Name 3 types of dinosaur species" },
  { "id": 445, "question": "Name 3 characters from Marvel's Avengers" },
  { "id": 446, "question": "Name 3 types of precious stones" },
  { "id": 447, "question": "Name 3 famous architects" },
  { "id": 448, "question": "Name 3 items found in a gym locker" },
  { "id": 449, "question": "Name 3 types of spicy peppers" },
  { "id": 450, "question": "Name 3 countries that border India" },
  { "id": 451, "question": "Name 3 types of human emotions" },
  { "id": 452, "question": "Name 3 items found in a bakery" },
  { "id": 453, "question": "Name 3 types of martial arts styles" },
  { "id": 454, "question": "Name 3 famous painters from the Renaissance" },
  { "id": 455, "question": "Name 3 items found in a hotel lobby" },
  { "id": 456, "question": "Name 3 types of weather patterns" },
  { "id": 457, "question": "Name 3 countries that start with 'P'" },
  { "id": 458, "question": "Name 3 items found in a library" },
  { "id": 459, "question": "Name 3 types of musical notation" },
  { "id": 460, "question": "Name 3 famous world landmarks in Asia" },
  { "id": 461, "question": "Name 3 types of breakfast cereals" },
  { "id": 462, "question": "Name 3 items found in a hospital room" },
  { "id": 463, "question": "Name 3 types of boat vessels" },
  { "id": 464, "question": "Name 3 countries that are landlocked" },
  { "id": 465, "question": "Name 3 items found in a kitchen drawer" },
  { "id": 466, "question": "Name 3 types of geometric angles" },
  { "id": 467, "question": "Name 3 famous American authors" },
  { "id": 468, "question": "Name 3 items found at a construction site" },
  { "id": 469, "question": "Name 3 types of birds of prey" },
  { "id": 470, "question": "Name 3 countries in South America" },
  { "id": 471, "question": "Name 3 types of card games" },
  { "id": 472, "question": "Name 3 items found in a car's glovebox" },
  { "id": 473, "question": "Name 3 types of constellations" },
  { "id": 474, "question": "Name 3 famous explorers of the Americas" },
  { "id": 475, "question": "Name 3 items found in a school classroom" },
  { "id": 476, "question": "Name 3 types of winter weather" },
  { "id": 477, "question": "Name 3 countries that start with 'R'" },
  { "id": 478, "question": "Name 3 items found in a dentist's office" },
  { "id": 479, "question": "Name 3 types of fabric textures" },
  { "id": 480, "question": "Name 3 famous historical queens" },
  { "id": 481, "question": "Name 3 items found in a post office" },
  { "id": 482, "question": "Name 3 types of nocturnal animals" },
  { "id": 483, "question": "Name 3 countries that border the Mediterranean Sea" },
  { "id": 484, "question": "Name 3 items found in a vanity" },
  { "id": 485, "question": "Name 3 types of dance genres" },
  { "id": 486, "question": "Name 3 famous scientific inventions" },
  { "id": 487, "question": "Name 3 items found in a jewelry store" },
  { "id": 488, "question": "Name 3 types of renewable energy" },
  { "id": 489, "question": "Name 3 countries in the Middle East" },
  { "id": 490, "question": "Name 3 items found at a hair salon" },
  { "id": 491, "question": "Name 3 types of clouds in the sky" },
  { "id": 492, "question": "Name 3 famous British monarchs" },
  { "id": 493, "question": "Name 3 items found in a garden shed" },
  { "id": 494, "question": "Name 3 types of farm machinery" },
  { "id": 495, "question": "Name 3 countries that start with 'G'" },
  { "id": 496, "question": "Name 3 items found in a nursery room" },
  { "id": 497, "question": "Name 3 types of computer hardware" },
  { "id": 498, "question": "Name 3 famous world capitals in Europe" },
  { "id": 499, "question": "Name 3 items found in a bar" },
  { "id": 500, "question": "Name 3 types of large cats" },
  { "id": 501, "question": "Name 3 countries in Africa" },
  { "id": 502, "question": "Name 3 items found in a briefcase" },
  { "id": 503, "question": "Name 3 types of pasta shapes" },
  { "id": 504, "question": "Name 3 famous classical musicians" },
  { "id": 505, "question": "Name 3 items found in a laundry room" },
  { "id": 506, "question": "Name 3 types of insects with wings" },
  { "id": 507, "question": "Name 3 countries that start with 'T'" },
  { "id": 508, "question": "Name 3 items found in a purse" },
  { "id": 509, "question": "Name 3 types of trees with needles" },
  { "id": 110, "question": "Name 3 famous movie directors" },
  { "id": 511, "question": "Name 3 items found in a wallet" },
  { "id": 512, "question": "Name 3 types of citrus trees" },
  { "id": 513, "question": "Name 3 countries in Central America" },
  { "id": 514, "question": "Name 3 items found in a garage" },
  { "id": 515, "question": "Name 3 types of sea shells" },
  { "id": 516, "question": "Name 3 famous Olympic athletes" },
  { "id": 517, "question": "Name 3 items found in a pantry" },
  { "id": 518, "question": "Name 3 types of berries" },
  { "id": 519, "question": "Name 3 countries that start with 'M'" },
  { "id": 520, "question": "Name 3 items found in a backpack" },
  { "id": 521, "question": "Name 3 types of flowers that are red" },
  { "id": 522, "question": "Name 3 famous actors from the 90s" },
  { "id": 523, "question": "Name 3 items found on a nightstand" },
  { "id": 524, "question": "Name 3 types of fish found in the ocean" },
  { "id": 525, "question": "Name 3 countries in Southeast Asia" },
  { "id": 526, "question": "Name 3 items found in a bathroom cabinet" },
  { "id": 527, "question": "Name 3 types of desert plants" },
  { "id": 528, "question": "Name 3 famous songs from the 70s" },
  { "id": 529, "question": "Name 3 items found in a messy room" },
  { "id": 530, "question": "Name 3 types of snakes that are venomous" },
  { "id": 531, "question": "Name 3 countries that start with 'L'" },
  { "id": 532, "question": "Name 3 items found in a recycling bin" },
  { "id": 533, "question": "Name 3 types of beans" },
  { "id": 534, "question": "Name 3 famous historical inventors" },
  { "id": 535, "question": "Name 3 items found in a junk drawer" },
  { "id": 536, "question": "Name 3 types of wind instruments" },
  { "id": 537, "question": "Name 3 countries in East Africa" },
  { "id": 538, "question": "Name 3 items found in a refrigerator door" },
  { "id": 539, "question": "Name 3 types of bread rolls" },
  { "id": 540, "question": "Name 3 famous books by Charles Dickens" },
  { "id": 541, "question": "Name 3 items found in a closet" },
  { "id": 542, "question": "Name 3 types of primates" },
  { "id": 543, "question": "Name 3 countries that start with 'N'" },
  { "id": 544, "question": "Name 3 items found in a diaper bag" },
  { "id": 545, "question": "Name 3 types of summer fruits" },
  { "id": 546, "question": "Name 3 famous comedians" },
  { "id": 547, "question": "Name 3 items found in a craft store" },
  { "id": 548, "question": "Name 3 types of indoor plants" },
  { "id": 549, "question": "Name 3 countries that border Canada" },
  { "id": 550, "question": "Name 3 items found in a toolbox tray" },
  { "id": 551, "question": "Name 3 types of kitchen utensils" },
  { "id": 552, "question": "Name 3 famous female singers from the 2000s" },
  { "id": 553, "question": "Name 3 items found in an office lobby" },
  { "id": 554, "question": "Name 3 types of cheese from France" },
  { "id": 555, "question": "Name 3 countries in the Balkans" },
  { "id": 556, "question": "Name 3 items found on a cruise ship" },
  { "id": 557, "question": "Name 3 types of aquatic birds" },
  { "id": 558, "question": "Name 3 famous movies from the 80s" },
  { "id": 559, "question": "Name 3 items found in a hiking pack" },
  { "id": 560, "question": "Name 3 types of tea ceremonies" },
  { "id": 561, "question": "Name 3 countries that start with 'E'" },
  { "id": 562, "question": "Name 3 items found in a makeup kit" },
  { "id": 563, "question": "Name 3 types of architectural styles" },
  { "id": 564, "question": "Name 3 famous paintings by Van Gogh" },
  { "id": 565, "question": "Name 3 items found in a basement workshop" },
  { "id": 566, "question": "Name 3 types of flightless birds" },
  { "id": 567, "question": "Name 3 countries in West Africa" },
  { "id": 568, "question": "Name 3 items found in a first-aid box" },
  { "id": 569, "question": "Name 3 types of pasta noodles" },
  { "id": 570, "question": "Name 3 famous sports teams from New York" },
  { "id": 571, "question": "Name 3 items found in a desk drawer" },
  { "id": 572, "question": "Name 3 types of rock music subgenres" },
  { "id": 573, "question": "Name 3 countries that border the Baltic Sea" },
  { "id": 574, "question": "Name 3 items found in a beach bag" },
  { "id": 575, "question": "Name 3 types of edible seeds" },
  { "id": 576, "question": "Name 3 famous landmarks in London" },
  { "id": 577, "question": "Name 3 items found in a jewelry box" },
  { "id": 578, "question": "Name 3 types of social media posts" },
  { "id": 579, "question": "Name 3 countries that start with 'H'" },
  { "id": 580, "question": "Name 3 items found in a coffee shop" },
  { "id": 581, "question": "Name 3 types of weather forecasts" },
  { "id": 582, "question": "Name 3 famous people from history named George" },
  { "id": 583, "question": "Name 3 items found in a gym bag" },
  { "id": 584, "question": "Name 3 types of winter coats" },
  { "id": 585, "question": "Name 3 countries in the Himalayas" },
  { "id": 586, "question": "Name 3 items found on a picnic blanket" },
  { "id": 587, "question": "Name 3 types of sea life that glow" },
  { "id": 588, "question": "Name 3 famous buildings in New York City" },
  { "id": 589, "question": "Name 3 items found in a teacher's desk" },
  { "id": 590, "question": "Name 3 types of craft beers" },
  { "id": 591, "question": "Name 3 countries that start with 'K'" },
  { "id": 592, "question": "Name 3 items found in a sewing room" },
  { "id": 593, "question": "Name 3 types of geometric shapes with 4 sides" },
  { "id": 594, "question": "Name 3 famous writers of mystery novels" },
  { "id": 595, "question": "Name 3 items found in a car's trunk" },
  { "id": 596, "question": "Name 3 types of reptiles that live in water" },
  { "id": 597, "question": "Name 3 countries in the Arctic Circle" },
  { "id": 598, "question": "Name 3 items found in a student's locker" },
  { "id": 599, "question": "Name 3 types of fruit juices" },
  { "id": 600, "question": "Name 3 famous world-renowned chefs" },
  { "id": 601, "question": "Name 3 types of noble gases" },
  { "id": 602, "question": "Name 3 luxury car brands" },
  { "id": 603, "question": "Name 3 famous psychologists" },
  { "id": 604, "question": "Name 3 types of bridge types" },
  { "id": 605, "question": "Name 3 cities in California" },
  { "id": 606, "question": "Name 3 brands of bottled water" },
  { "id": 607, "question": "Name 3 characters from The Office" },
  { "id": 608, "question": "Name 3 types of volcanic rocks" },
  { "id": 609, "question": "Name 3 famous world-record holders" },
  { "id": 610, "question": "Name 3 parts of a flower" },
  { "id": 611, "question": "Name 3 types of coffee beans" },
  { "id": 612, "question": "Name 3 countries that border Brazil" },
  { "id": 613, "question": "Name 3 famous female world leaders" },
  { "id": 614, "question": "Name 3 items found in a spaceship" },
  { "id": 615, "question": "Name 3 types of renewable energy" },
  { "id": 616, "question": "Name 3 characters from Toy Story" },
  { "id": 617, "question": "Name 3 types of dental tools" },
  { "id": 618, "question": "Name 3 countries in North Africa" },
  { "id": 619, "question": "Name 3 brands of designer shoes" },
  { "id": 620, "question": "Name 3 types of human tissue" },
  { "id": 621, "question": "Name 3 items found in a chemistry lab" },
  { "id": 622, "question": "Name 3 types of classical dance" },
  { "id": 623, "question": "Name 3 countries that start with 'U'" },
  { "id": 624, "question": "Name 3 famous explorers of the Antarctic" },
  { "id": 625, "question": "Name 3 types of nuts used in baking" },
  { "id": 626, "question": "Name 3 items found in a darkroom" },
  { "id": 627, "question": "Name 3 types of infectious diseases" },
  { "id": 628, "question": "Name 3 famous bridges in the US" },
  { "id": 629, "question": "Name 3 items found in a doctor's waiting room" },
  { "id": 630, "question": "Name 3 types of string instruments" },
  { "id": 631, "question": "Name 3 countries that start with 'V'" },
  { "id": 632, "question": "Name 3 items found in a hardware store aisle" },
  { "id": 633, "question": "Name 3 types of nocturnal birds" },
  { "id": 634, "question": "Name 3 famous novels by Ernest Hemingway" },
  { "id": 635, "question": "Name 3 items found in a pilot's cockpit" },
  { "id": 636, "question": "Name 3 types of digital file extensions" },
  { "id": 637, "question": "Name 3 countries in the European Union" },
  { "id": 638, "question": "Name 3 items found in a craft box" },
  { "id": 639, "question": "Name 3 types of Olympic track events" },
  { "id": 640, "question": "Name 3 famous jazz musicians" },
  { "id": 641, "question": "Name 3 items found in a hotel minibar" },
  { "id": 642, "question": "Name 3 types of clouds" },
  { "id": 643, "question": "Name 3 countries that border Russia" },
  { "id": 644, "question": "Name 3 items found in a gym locker room" },
  { "id": 645, "question": "Name 3 types of weather measuring tools" },
  { "id": 646, "question": "Name 3 famous astronauts" },
  { "id": 647, "question": "Name 3 items found in a jewelry workshop" },
  { "id": 648, "question": "Name 3 types of flightless insects" },
  { "id": 649, "question": "Name 3 countries that start with 'Y'" },
  { "id": 650, "question": "Name 3 items found in a basement storage" },
  { "id": 651, "question": "Name 3 types of deep-sea fish" },
  { "id": 652, "question": "Name 3 famous movie musicals" },
  { "id": 653, "question": "Name 3 items found in a theater backstage" },
  { "id": 654, "question": "Name 3 types of architectural columns" },
  { "id": 655, "question": "Name 3 countries in the United Kingdom" },
  { "id": 656, "question": "Name 3 items found in a bakery display" },
  { "id": 657, "question": "Name 3 types of non-venomous snakes" },
  { "id": 658, "question": "Name 3 famous sitcom families" },
  { "id": 659, "question": "Name 3 items found in a bicycle repair kit" },
  { "id": 660, "question": "Name 3 types of cold-weather fruits" },
  { "id": 661, "question": "Name 3 countries that start with 'O'" },
  { "id": 662, "question": "Name 3 items found in a school cafeteria" },
  { "id": 663, "question": "Name 3 types of heavy machinery" },
  { "id": 664, "question": "Name 3 famous characters from Greek myths" },
  { "id": 665, "question": "Name 3 items found in a garden shed" },
  { "id": 666, "question": "Name 3 types of computer viruses" },
  { "id": 667, "question": "Name 3 countries that border the Indian Ocean" },
  { "id": 668, "question": "Name 3 items found in a fashion designer's studio" },
  { "id": 669, "question": "Name 3 types of deciduous trees" },
  { "id": 670, "question": "Name 3 famous albums by Michael Jackson" },
  { "id": 671, "question": "Name 3 items found in a campsite cooler" },
  { "id": 672, "question": "Name 3 types of tropical storms" },
  { "id": 673, "question": "Name 3 countries that start with 'W'" },
  { "id": 674, "question": "Name 3 items found in a makeup vanity" },
  { "id": 675, "question": "Name 3 types of urban transport" },
  { "id": 676, "question": "Name 3 famous landmarks in Italy" },
  { "id": 677, "question": "Name 3 items found in a laundry basket" },
  { "id": 678, "question": "Name 3 types of carnivorous animals" },
  { "id": 679, "question": "Name 3 countries in West Asia" },
  { "id": 680, "question": "Name 3 items found in a professional kitchen" },
  { "id": 681, "question": "Name 3 types of sourdough bread" },
  { "id": 682, "question": "Name 3 famous female athletes" },
  { "id": 683, "question": "Name 3 items found in a home office" },
  { "id": 684, "question": "Name 3 types of winter coats" },
  { "id": 685, "question": "Name 3 countries that start with 'F'" },
  { "id": 686, "question": "Name 3 items found in a nursery" },
  { "id": 687, "question": "Name 3 types of marine plants" },
  { "id": 688, "question": "Name 3 famous movie quotes" },
  { "id": 689, "question": "Name 3 items found in a picnic basket" },
  { "id": 690, "question": "Name 3 types of artisan cheeses" },
  { "id": 691, "question": "Name 3 countries that border Mexico" },
  { "id": 692, "question": "Name 3 items found in a toolbox" },
  { "id": 693, "question": "Name 3 types of light bulbs" },
  { "id": 694, "question": "Name 3 famous scientists from history" },
  { "id": 695, "question": "Name 3 items found in a school bus" },
  { "id": 696, "question": "Name 3 types of primates" },
  { "id": 697, "question": "Name 3 countries in Southeast Asia" },
  { "id": 698, "question": "Name 3 items found in a post office box" },
  { "id": 699, "question": "Name 3 types of electronic music" },
  { "id": 700, "question": "Name 3 famous buildings in Paris" },
  { "id": 701, "question": "Name 3 items found in a coffee bar" },
  { "id": 702, "question": "Name 3 types of green vegetables" },
  { "id": 703, "question": "Name 3 countries that start with 'J'" },
  { "id": 704, "question": "Name 3 items found in a child's toy box" },
  { "id": 705, "question": "Name 3 types of mountain ranges" },
  { "id": 706, "question": "Name 3 famous poets from the UK" },
  { "id": 707, "question": "Name 3 items found in a library's reference section" },
  { "id": 708, "question": "Name 3 types of predatory birds" },
  { "id": 709, "question": "Name 3 countries that border Germany" },
  { "id": 710, "question": "Name 3 items found in a car's trunk" },
  { "id": 711, "question": "Name 3 types of ball sports" },
  { "id": 712, "question": "Name 3 famous paintings in the Louvre" },
  { "id": 713, "question": "Name 3 items found in a survival kit" },
  { "id": 714, "question": "Name 3 types of kitchen knives" },
  { "id": 715, "question": "Name 3 countries that start with 'K'" },
  { "id": 716, "question": "Name 3 items found in a desk drawer" },
  { "id": 717, "question": "Name 3 types of scientific theories" },
  { "id": 718, "question": "Name 3 famous people named William" },
  { "id": 719, "question": "Name 3 items found in a bathroom cabinet" },
  { "id": 720, "question": "Name 3 types of fabric patterns" },
  { "id": 721, "question": "Name 3 countries in South America" },
  { "id": 722, "question": "Name 3 items found on a construction site" },
  { "id": 723, "question": "Name 3 types of ancient weapons" },
  { "id": 724, "question": "Name 3 famous world-renowned chefs" },
  { "id": 725, "question": "Name 3 items found in a gym bag" },
  { "id": 726, "question": "Name 3 types of insects with stingers" },
  { "id": 727, "question": "Name 3 countries that start with 'Q'" },
  { "id": 728, "question": "Name 3 items found in a pantry" },
  { "id": 729, "question": "Name 3 types of fruit that are yellow" },
  { "id": 730, "question": "Name 3 famous films from the 1990s" },
  { "id": 731, "question": "Name 3 items found in a briefcase" },
  { "id": 732, "question": "Name 3 types of household pets" },
  { "id": 733, "question": "Name 3 countries that border China" },
  { "id": 734, "question": "Name 3 items found in a closet" },
  { "id": 735, "question": "Name 3 types of sea life with tentacles" },
  { "id": 736, "question": "Name 3 famous books by Stephen King" },
  { "id": 737, "question": "Name 3 items found in a laundry room" },
  { "id": 738, "question": "Name 3 types of pasta" },
  { "id": 739, "question": "Name 3 countries that start with 'Z'" },
  { "id": 740, "question": "Name 3 items found in a car's glovebox" },
  { "id": 741, "question": "Name 3 types of lizard species" },
  { "id": 742, "question": "Name 3 famous bands from the 70s" },
  { "id": 743, "question": "Name 3 items found in a hotel lobby" },
  { "id": 744, "question": "Name 3 types of breakfast foods" },
  { "id": 745, "question": "Name 3 countries in the Caribbean" },
  { "id": 746, "question": "Name 3 items found in a pharmacy aisle" },
  { "id": 747, "question": "Name 3 types of dinosaurs" },
  { "id": 748, "question": "Name 3 famous leaders from the 20th century" },
  { "id": 749, "question": "Name 3 items found in a backpack" },
  { "id": 750, "question": "Name 3 types of weather patterns" },
  { "id": 751, "question": "Name 3 countries that border Canada" },
  { "id": 752, "question": "Name 3 items found in a vanity" },
  { "id": 753, "question": "Name 3 types of dance" },
  { "id": 754, "question": "Name 3 famous scientific inventions" },
  { "id": 755, "question": "Name 3 items found in a jewelry store" },
  { "id": 756, "question": "Name 3 types of renewable energy" },
  { "id": 757, "question": "Name 3 countries in the Middle East" },
  { "id": 758, "question": "Name 3 items found at a hair salon" },
  { "id": 759, "question": "Name 3 types of clouds" },
  { "id": 760, "question": "Name 3 famous British monarchs" },
  { "id": 761, "question": "Name 3 items found in a garden shed" },
  { "id": 762, "question": "Name 3 types of farm machinery" },
  { "id": 763, "question": "Name 3 countries that start with 'G'" },
  { "id": 764, "question": "Name 3 items found in a nursery" },
  { "id": 765, "question": "Name 3 types of computer hardware" },
  { "id": 766, "question": "Name 3 famous world capitals in Europe" },
  { "id": 767, "question": "Name 3 items found in a bar" },
  { "id": 768, "question": "Name 3 types of large cats" },
  { "id": 769, "question": "Name 3 countries in Africa" },
  { "id": 770, "question": "Name 3 items found in a briefcase" },
  { "id": 771, "question": "Name 3 types of pasta shapes" },
  { "id": 772, "question": "Name 3 famous classical musicians" },
  { "id": 773, "question": "Name 3 items found in a laundry room" },
  { "id": 774, "question": "Name 3 types of insects with wings" },
  { "id": 775, "question": "Name 3 countries that start with 'T'" },
  { "id": 776, "question": "Name 3 items found in a purse" },
  { "id": 777, "question": "Name 3 types of trees with needles" },
  { "id": 778, "question": "Name 3 famous movie directors" },
  { "id": 779, "question": "Name 3 items found in a wallet" },
  { "id": 780, "question": "Name 3 types of citrus trees" },
  { "id": 781, "question": "Name 3 countries in Central America" },
  { "id": 782, "question": "Name 3 items found in a garage" },
  { "id": 783, "question": "Name 3 types of sea shells" },
  { "id": 784, "question": "Name 3 famous Olympic athletes" },
  { "id": 785, "question": "Name 3 items found in a pantry" },
  { "id": 786, "question": "Name 3 types of berries" },
  { "id": 787, "question": "Name 3 countries that start with 'M'" },
  { "id": 788, "question": "Name 3 items found in a backpack" },
  { "id": 789, "question": "Name 3 types of flowers that are red" },
  { "id": 790, "question": "Name 3 famous actors from the 90s" },
  { "id": 791, "question": "Name 3 items found on a nightstand" },
  { "id": 792, "question": "Name 3 types of fish found in the ocean" },
  { "id": 793, "question": "Name 3 countries in Southeast Asia" },
  { "id": 794, "question": "Name 3 items found in a bathroom cabinet" },
  { "id": 795, "question": "Name 3 types of desert plants" },
  { "id": 796, "question": "Name 3 famous songs from the 70s" },
  { "id": 797, "question": "Name 3 items found in a messy room" },
  { "id": 798, "question": "Name 3 types of snakes that are venomous" },
  { "id": 799, "question": "Name 3 countries that start with 'L'" },
  { "id": 800, "question": "Name 3 items found in a recycling bin" },
  { "id": 801, "question": "Name 3 types of Olympic martial arts" },
  { "id": 802, "question": "Name 3 ingredients in a traditional Pesto" },
  { "id": 803, "question": "Name 3 countries that border Thailand" },
  { "id": 804, "question": "Name 3 types of classical architectural orders" },
  { "id": 805, "question": "Name 3 characters from the Marvel Cinematic Universe" },
  { "id": 806, "question": "Name 3 methods of heat transfer" },
  { "id": 807, "question": "Name 3 types of cryptographic algorithms" },
  { "id": 808, "question": "Name 3 famous landmarks in Australia" },
  { "id": 809, "question": "Name 3 types of specialized surgical tools" },
  { "id": 810, "question": "Name 3 countries in the G7" },
  { "id": 811, "question": "Name 3 types of sushi grade fish" },
  { "id": 812, "question": "Name 3 historical figures on US bank notes" },
  { "id": 813, "question": "Name 3 types of poetic meter" },
  { "id": 814, "question": "Name 3 brands of high-end watches" },
  { "id": 815, "question": "Name 3 organs in the endocrine system" },
  { "id": 816, "question": "Name 3 countries that start with 'N'" },
  { "id": 817, "question": "Name 3 types of legal defenses" },
  { "id": 818, "question": "Name 3 winners of the Tour de France" },
  { "id": 819, "question": "Name 3 types of igneous rocks" },
  { "id": 820, "question": "Name 3 characters from Game of Thrones" },
  { "id": 821, "question": "Name 3 types of musical intervals" },
  { "id": 822, "question": "Name 3 countries in the Arabian Peninsula" },
  { "id": 823, "question": "Name 3 types of pasta sauces" },
  { "id": 824, "question": "Name 3 famous world-renowned architects" },
  { "id": 825, "question": "Name 3 types of atmospheric pressure systems" },
  { "id": 826, "question": "Name 3 items found in a pilot's flight bag" },
  { "id": 827, "question": "Name 3 types of coffee brewing methods" },
  { "id": 828, "question": "Name 3 countries that border the Black Sea" },
  { "id": 829, "question": "Name 3 famous female authors of the 19th century" },
  { "id": 830, "question": "Name 3 types of cyber security threats" },
  { "id": 831, "question": "Name 3 items found in an archery kit" },
  { "id": 832, "question": "Name 3 types of financial market indices" },
  { "id": 833, "question": "Name 3 countries in the Baltic region" },
  { "id": 834, "question": "Name 3 types of non-Newtonian fluids" },
  { "id": 835, "question": "Name 3 famous space telescopes" },
  { "id": 836, "question": "Name 3 items found in a carpenter's belt" },
  { "id": 837, "question": "Name 3 types of cognitive biases" },
  { "id": 838, "question": "Name 3 countries that border Egypt" },
  { "id": 839, "question": "Name 3 famous silent film actors" },
  { "id": 840, "question": "Name 3 types of statistical distributions" },
  { "id": 841, "question": "Name 3 items found in a chemistry distillation setup" },
  { "id": 842, "question": "Name 3 types of government structures" },
  { "id": 843, "question": "Name 3 countries in the Himalayan mountain range" },
  { "id": 844, "question": "Name 3 types of bridge load stresses" },
  { "id": 845, "question": "Name 3 famous mathematicians from history" },
  { "id": 846, "question": "Name 3 items found in a watchmaker's toolkit" },
  { "id": 847, "question": "Name 3 types of specialized camera lenses" },
  { "id": 848, "question": "Name 3 countries that border Vietnam" },
  { "id": 849, "question": "Name 3 famous philosophers of the Enlightenment" },
  { "id": 850, "question": "Name 3 types of soil horizons" },
  { "id": 851, "question": "Name 3 items found in a geologist's field bag" },
  { "id": 852, "question": "Name 3 types of musical time signatures" },
  { "id": 853, "question": "Name 3 countries in Central Asia" },
  { "id": 854, "question": "Name 3 types of chemical reaction catalysts" },
  { "id": 855, "question": "Name 3 famous landmarks in South America" },
  { "id": 856, "question": "Name 3 items found in a sailing boat's cabin" },
  { "id": 857, "question": "Name 3 types of structural engineering materials" },
  { "id": 858, "question": "Name 3 countries that border South Africa" },
  { "id": 859, "question": "Name 3 famous Impressionist painters" },
  { "id": 860, "question": "Name 3 types of psychological defense mechanisms" },
  { "id": 861, "question": "Name 3 items found in a locksmith's kit" },
  { "id": 862, "question": "Name 3 types of aerodynamic forces" },
  { "id": 863, "question": "Name 3 countries in Western Europe" },
  { "id": 864, "question": "Name 3 types of binary logic gates" },
  { "id": 865, "question": "Name 3 famous historical documents" },
  { "id": 866, "question": "Name 3 items found in a darkroom for film" },
  { "id": 867, "question": "Name 3 types of genetic mutations" },
  { "id": 868, "question": "Name 3 countries that border Turkey" },
  { "id": 869, "question": "Name 3 famous Surrealist artists" },
  { "id": 870, "question": "Name 3 types of computer network topologies" },
  { "id": 871, "question": "Name 3 items found in a tailor's shop" },
  { "id": 872, "question": "Name 3 types of historical sailing ships" },
  { "id": 873, "question": "Name 3 countries in the Sahara Desert region" },
  { "id": 874, "question": "Name 3 types of ancient Greek columns" },
  { "id": 875, "question": "Name 3 famous female mathematicians" },
  { "id": 876, "question": "Name 3 items found in a barista's station" },
  { "id": 877, "question": "Name 3 types of economic theories" },
  { "id": 878, "question": "Name 3 countries that border Peru" },
  { "id": 879, "question": "Name 3 famous classical violinists" },
  { "id": 880, "question": "Name 3 types of cloud storage providers" },
  { "id": 881, "question": "Name 3 items found in a mechanic's pit" },
  { "id": 882, "question": "Name 3 types of astronomical nebulae" },
  { "id": 883, "question": "Name 3 countries in Northern Europe" },
  { "id": 884, "question": "Name 3 types of biological biomes" },
  { "id": 885, "question": "Name 3 famous world-renowned physicists" },
  { "id": 886, "question": "Name 3 items found in a veterinarian's clinic" },
  { "id": 887, "question": "Name 3 types of mathematical constants" },
  { "id": 888, "question": "Name 3 countries that border Poland" },
  { "id": 889, "question": "Name 3 famous Renaissance sculptors" },
  { "id": 890, "question": "Name 3 types of social influence (psychology)" },
  { "id": 891, "question": "Name 3 items found in a stage lighting rig" },
  { "id": 892, "question": "Name 3 types of subatomic particles" },
  { "id": 893, "question": "Name 3 countries in the Amazon Basin" },
  { "id": 894, "question": "Name 3 types of volcanic mountains" },
  { "id": 895, "question": "Name 3 famous jazz saxophonists" },
  { "id": 896, "question": "Name 3 items found in a printmaking studio" },
  { "id": 897, "question": "Name 3 types of programming paradigms" },
  { "id": 898, "question": "Name 3 countries that border Iran" },
  { "id": 899, "question": "Name 3 famous explorers of the interior of Africa" },
  { "id": 900, "question": "Name 3 types of tectonic plate boundaries" },
  { "id": 901, "question": "Name 3 items found in an apothecary" },
  { "id": 902, "question": "Name 3 types of specialized cheeses from Spain" },
  { "id": 903, "question": "Name 3 countries in the South Pacific" },
  { "id": 904, "question": "Name 3 types of legal contracts" },
  { "id": 905, "question": "Name 3 famous modern architects" },
  { "id": 906, "question": "Name 3 items found in a baker's proofer" },
  { "id": 907, "question": "Name 3 types of logic puzzles" },
  { "id": 908, "question": "Name 3 countries that border Argentina" },
  { "id": 909, "question": "Name 3 famous operatic tenors" },
  { "id": 910, "question": "Name 3 types of digital marketing strategies" },
  { "id": 911, "question": "Name 3 items found in a distillery" },
  { "id": 912, "question": "Name 3 types of cloud computing models" },
  { "id": 913, "question": "Name 3 countries in the Horn of Africa" },
  { "id": 914, "question": "Name 3 types of structural load" },
  { "id": 915, "question": "Name 3 famous female scientists of the 20th century" },
  { "id": 916, "question": "Name 3 items found in a goldsmith's bench" },
  { "id": 917, "question": "Name 3 types of cryptography" },
  { "id": 918, "question": "Name 3 countries that border Ukraine" },
  { "id": 919, "question": "Name 3 famous Russian novelists" },
  { "id": 920, "question": "Name 3 types of astronomical coordinate systems" },
  { "id": 921, "question": "Name 3 items found in a dental hygiene kit" },
  { "id": 922, "question": "Name 3 types of psychological disorders" },
  { "id": 923, "question": "Name 3 countries in the Balkans" },
  { "id": 924, "question": "Name 3 types of engineering software" },
  { "id": 925, "question": "Name 3 famous world heritage sites in India" },
  { "id": 926, "question": "Name 3 items found in a flight attendant's galley" },
  { "id": 927, "question": "Name 3 types of specialized fishing lures" },
  { "id": 928, "question": "Name 3 countries that border Greece" },
  { "id": 929, "question": "Name 3 famous American transcendentalist writers" },
  { "id": 930, "question": "Name 3 types of sound waves" },
  { "id": 931, "question": "Name 3 items found in a pool hall" },
  { "id": 932, "question": "Name 3 types of scientific classification (Taxonomy)" },
  { "id": 933, "question": "Name 3 countries in the Caucasus region" },
  { "id": 934, "question": "Name 3 types of specialized bridge joints" },
  { "id": 935, "question": "Name 3 famous polymaths" },
  { "id": 936, "question": "Name 3 items found in a violin maker's workshop" },
  { "id": 937, "question": "Name 3 types of chemical isotopes" },
  { "id": 938, "question": "Name 3 countries that border Nigeria" },
  { "id": 939, "question": "Name 3 famous composers of the Baroque period" },
  { "id": 940, "question": "Name 3 types of architectural floor plans" },
  { "id": 941, "question": "Name 3 items found in a film director's monitor bag" },
  { "id": 942, "question": "Name 3 types of biological kingdoms" },
  { "id": 943, "question": "Name 3 countries in the Andes mountains" },
  { "id": 944, "question": "Name 3 types of mathematical proofs" },
  { "id": 945, "question": "Name 3 famous world leaders of the 19th century" },
  { "id": 946, "question": "Name 3 items found in a blacksmith's forge" },
  { "id": 947, "question": "Name 3 types of celestial bodies" },
  { "id": 948, "question": "Name 3 countries that border Pakistan" },
  { "id": 949, "question": "Name 3 famous philosophers from Asia" },
  { "id": 950, "question": "Name 3 types of human muscle tissue" },
  { "id": 951, "question": "Name 3 items found in a gardener's tool belt" },
  { "id": 952, "question": "Name 3 types of wind turbines" },
  { "id": 953, "question": "Name 3 countries in the Nile River basin" },
  { "id": 954, "question": "Name 3 types of chemical solutions" },
  { "id": 955, "question": "Name 3 famous world monuments in Egypt" },
  { "id": 956, "question": "Name 3 items found in a sommelier's kit" },
  { "id": 957, "question": "Name 3 types of specialized drill bits" },
  { "id": 958, "question": "Name 3 countries that border Ethiopia" },
  { "id": 959, "question": "Name 3 famous Japanese directors" },
  { "id": 960, "question": "Name 3 types of economic indicators" },
  { "id": 961, "question": "Name 3 items found in a data center" },
  { "id": 962, "question": "Name 3 types of particle accelerators" },
  { "id": 963, "question": "Name 3 countries in the Arctic Circle" },
  { "id": 964, "question": "Name 3 types of specialized surgical sutures" },
  { "id": 965, "question": "Name 3 famous world explorers of the 20th century" },
  { "id": 966, "question": "Name 3 items found in a sound recording studio" },
  { "id": 967, "question": "Name 3 types of computer memory" },
  { "id": 968, "question": "Name 3 countries that border Spain" },
  { "id": 969, "question": "Name 3 famous abstract expressionist painters" },
  { "id": 970, "question": "Name 3 types of astronomical orbits" },
  { "id": 971, "question": "Name 3 items found in a high-end restaurant cellar" },
  { "id": 972, "question": "Name 3 types of social media algorithms" },
  { "id": 973, "question": "Name 3 countries in the Amazon rainforest" },
  { "id": 974, "question": "Name 3 types of botanical gardens" },
  { "id": 975, "question": "Name 3 famous world-renowned sculptors" },
  { "id": 976, "question": "Name 3 items found in an airplane's cockpit console" },
  { "id": 977, "question": "Name 3 types of specialized research microscopes" },
  { "id": 978, "question": "Name 3 countries that border Switzerland" },
  { "id": 979, "question": "Name 3 famous world explorers of the 15th century" },
  { "id": 980, "question": "Name 3 types of ocean currents" },
  { "id": 981, "question": "Name 3 items found in a master chef's pantry" },
  { "id": 982, "question": "Name 3 types of financial derivatives" },
  { "id": 983, "question": "Name 3 countries in the Mediterranean region" },
  { "id": 984, "question": "Name 3 types of specialized medical imaging" },
  { "id": 985, "question": "Name 3 famous world leaders of the 21st century" },
  { "id": 986, "question": "Name 3 items found in a professional artist's studio" },
  { "id": 987, "question": "Name 3 types of specialized software for design" },
  { "id": 988, "question": "Name 3 countries that border France" },
  { "id": 989, "question": "Name 3 famous world thinkers of the 20th century" },
  { "id": 990, "question": "Name 3 types of specialized global climate zones" },
  { "id": 991, "question": "Name 3 items found in a high-tech research facility" },
  { "id": 992, "question": "Name 3 types of specialized biological research tools" },
  { "id": 993, "question": "Name 3 countries in the Scandinavian region" },
  { "id": 994, "question": "Name 3 types of specialized engineering projects" },
  { "id": 995, "question": "Name 3 famous world explorers of the 19th century" },
  { "id": 996, "question": "Name 3 items found in a professional filmmaker's kit" },
  { "id": 997, "question": "Name 3 types of specialized computer hardware" },
  { "id": 998, "question": "Name 3 countries that border Italy" },
  { "id": 999, "question": "Name 3 famous world thinkers of the 19th century" },
  { "id": 1000, "question": "Name 3 types of specialized global weather events" }
];
