export const cardDrinkingGamePrompts: string[] = [
  "Everyone who is wearing a watch drinks",
  "Everyone who is wearing glasses drinks",
  "Everyone who checked their phone in the last 5 minutes drinks",
  "Everyone wearing black drinks",
  "Everyone wearing slippers or sandals drinks",
  "Everyone who arrived late drinks",
  "Everyone who drove here drinks water instead",
  "Everyone who lives nearby drinks",
  "Everyone who traveled the farthest drinks",
  "Everyone who is wearing a belt drinks",

  "The person who picked this card drinks",
  "The person to your left drinks",
  "The person to your right drinks",
  "Pick someone to drink with you",
  "Pick someone to drink twice",
  "Everyone except you drinks",
  "You drink for every sibling you have",
  "You drink if you’re the youngest here",
  "You drink if you’re the oldest here",
  "You drink if you’re single",

  "Compliment the person across from you or drink",
  "Say something nice about the host or drink",
  "Thank the person on your right or drink",
  "Tell a fun fact about yourself or drink",
  "Share an embarrassing story or drink",
  "Say your favorite food out loud or drink",
  "Say your favorite drink or drink",
  "Say your favorite movie or drink",
  "Say your favorite song or drink",
  "Say your favorite place or drink",

  "Drink if you’ve skipped a workout this week",
  "Drink if you’ve lied today",
  "Drink if you’ve ghosted someone",
  "Drink if you’ve stayed up past 3 AM this week",
  "Drink if you’ve ordered food delivery this week",
  "Drink if you’ve watched a show you didn’t finish",
  "Drink if you’ve been late to work or school",
  "Drink if you’ve pretended to be busy",
  "Drink if you’ve stalked someone online",
  "Drink if you’ve reread old messages",

  "Last person to touch the table drinks",
  "Last person to raise their hand drinks",
  "Last person to stand up drinks",
  "Last person to smile drinks",
  "Last person to say the host’s name drinks",
  "Everyone drinks one sip",
  "Everyone drinks two sips",
  "Everyone drinks except the card picker",
  "Everyone drinks if the picker drinks",
  "Everyone drinks if the picker refuses",

  "Make eye contact with someone for 5 seconds or drink",
  "Speak in an accent for one round or drink",
  "Stand up and spin once or drink",
  "Do a small dance move or drink",
  "Clap three times or drink",
  "Send a thumbs-up emoji to someone or drink",
  "Post a harmless story or drink",
  "Switch seats with someone or drink",
  "High-five two people or drink",
  "Smile until your next turn or drink",

  "Drink if you’ve played a drinking game before",
  "Drink if you’ve been tipsy in public",
  "Drink if you’ve laughed so hard you cried",
  "Drink if you’ve lost your phone before",
  "Drink if you’ve forgotten someone’s name",
  "Drink if you’ve fallen asleep somewhere random",
  "Drink if you’ve eaten something off the floor",
  "Drink if you’ve sent a message to the wrong person",
  "Drink if you’ve pretended to know something",
  "Drink if you’re having fun right now"
];