export const cardDrinkingGamePrompts: string[] = [
  "Everyone who is wearing a watch drinks",
  "Everyone who is wearing glasses drinks",
  "Everyone who checked their phone in the last 5 minutes drinks",
  "Everyone wearing black drinks",
  "Everyone wearing slippers or sandals drinks",
  "Everyone who arrived late drinks",
  "Everyone who drove here drinks water instead",
  "Everyone who lives nearby drinks",
  "Everyone who traveled the farthest drinks",
  "Everyone who is wearing a belt drinks",

  "The person who picked this card drinks",
  "The person to your left drinks",
  "The person to your right drinks",
  "Pick someone to drink with you",
  "Pick someone to drink twice",
  "Everyone except you drinks",
  "You drink for every sibling you have",
  "You drink if you’re the youngest here",
  "You drink if you’re the oldest here",
  "You drink if you’re single",
  "Compliment the person across from you or drink",
  "Say something nice about the host or drink",
  "Thank the person on your right or drink",
  "Tell a fun fact about yourself or drink",
  "Share an embarrassing story or drink",
  "Say your favorite food out loud or drink",
  "Say your favorite drink or drink",
  "Say your favorite movie or drink",
  "Say your favorite song or drink",
  "Say your favorite place or drink",
  "Drink if you’ve skipped a workout this week",
  "Drink if you’ve lied today",
  "Drink if you’ve ghosted someone",
  "Drink if you’ve stayed up past 3 AM this week",
  "Drink if you’ve ordered food delivery this week",
  "Drink if you’ve watched a show you didn’t finish",
  "Drink if you’ve been late to work or school",
  "Drink if you’ve pretended to be busy",
  "Drink if you’ve stalked someone online",
  "Drink if you’ve reread old messages",
  "Last person to touch the table drinks",
  "Last person to raise their hand drinks",
  "Last person to stand up drinks",
  "Last person to smile drinks",
  "Last person to say the host’s name drinks",
  "Everyone drinks one sip",
  "Everyone drinks two sips",
  "Everyone drinks except the card picker",
  "Everyone drinks if the picker drinks",
  "Everyone drinks if the picker refuses",
  "Make eye contact with someone for 5 seconds or drink",
  "Speak in an accent for one round or drink",
  "Stand up and spin once or drink",
  "Do a small dance move or drink",
  "Clap three times or drink",
  "Send a thumbs-up emoji to someone or drink",
  "Post a harmless story or drink",
  "Switch seats with someone or drink",
  "High-five two people or drink",
  "Smile until your next turn or drink",
  "Drink if you’ve played a drinking game before",
  "Drink if you’ve been tipsy in public",
  "Drink if you’ve laughed so hard you cried",
  "Drink if you’ve lost your phone before",
  "Drink if you’ve forgotten someone’s name",
  "Drink if you’ve fallen asleep somewhere random",
  "Drink if you’ve eaten something off the floor",
  "Drink if you’ve sent a message to the wrong person",
  "Drink if you’ve pretended to know something",
  "Drink if you’re having fun right now",
  "Everyone wearing glasses drinks",
  "The card picker drinks",
  "Everyone with a birthday this month drinks",
  "Compliment the person to your right or drink",
  "Everyone wearing blue drinks",
  "Take a sip if you've been on a roller coaster",
  "Tell a secret or take a drink",
  "Everyone who has a pet drinks",
  "The card picker takes 2 sips",
  "Everyone who has been abroad drinks",
  "Dance for 5 seconds or drink",
  "Everyone who has siblings drinks",
  "Share your last embarrassing moment or drink",
  "Everyone who likes pineapple on pizza drinks",
  "The person on your left drinks",
  "Imitate a celebrity or drink",
  "Everyone who has seen a scary movie recently drinks",
  "Tell a joke or drink",
  "Everyone wearing socks drinks",
  "Take a sip if you’ve ever gone camping",
  "Everyone who knows a magic trick drinks",
  "Sing the first line of a song or drink",
  "The card picker drinks twice",
  "Everyone who has been to a concert drinks",
  "Swap a seat with someone or drink",
  "Everyone who has a tattoo drinks",
  "Do 5 jumping jacks or drink",
  "Everyone who has used a dating app drinks",
  "The card picker chooses someone to drink",
  "Everyone who can whistle drinks",
  "Tell a lie convincingly or drink",
  "Everyone who has broken a bone drinks",
  "The person with the longest hair drinks",
  "Everyone who speaks more than one language drinks",
  "Make a funny face or drink",
  "Everyone wearing rings drinks",
  "Share a guilty pleasure or drink",
  "Everyone who has played a board game this week drinks",
  "The card picker drinks and chooses someone else to drink",
  "Everyone who has stayed awake all night drinks",
  "Give a toast or take a drink",
  "Everyone who likes coffee drinks",
  "Pretend to be an animal for 5 seconds or drink",
  "Everyone who has eaten sushi drinks",
  "The person who arrived last drinks",
  "Everyone who has a nickname drinks",
  "Say a tongue twister or drink",
  "Everyone who has sung karaoke drinks",
  "The card picker chooses someone to swap drinks with",
  "Everyone who has traveled by plane drinks",
  "Act like a pirate or drink",
  "Everyone who owns a car drinks",
  "The person wearing red drinks",
  "Everyone who has binge-watched a series drinks",
  "Tell a funny childhood story or drink",
  "Everyone who has a social media account drinks",
  "The card picker drinks if they laugh at their own joke",
  "Everyone who likes chocolate drinks",
  "Make a silly dance move or drink",
  "Everyone who has gone swimming this week drinks",
  "The card picker chooses someone to tell a joke or drink",
  "Everyone who has played video games drinks",
  "Act like a robot or drink",
  "Everyone who has eaten dessert today drinks",
  "The card picker drinks for each 'yes' answer",
  "Everyone who has been to a wedding drinks",
  "Imitate your favorite cartoon character or drink",
  "Everyone who likes spicy food drinks",
  "The card picker chooses someone to mimic an animal",
  "Everyone who has tried a new hobby this month drinks",
  "Sing a line from your favorite song or drink",
  "Everyone who has stayed in pajamas all day drinks",
  "The card picker drinks if they have a sweet tooth",
  "Everyone who owns a pet drinks",
  "Do 10 pushups or drink",
  "Everyone who has a lucky charm drinks",
  "The person with the shortest hair drinks",
  "Everyone who has cooked today drinks",
  "Share a random fact or drink",
  "Everyone who has seen a live performance drinks",
  "The card picker drinks and chooses someone to drink",
  "Everyone who has been to a beach drinks",
  "Pretend to speak in an accent or drink",
  "Everyone who has tried a new food this week drinks",
  "The card picker picks someone to take 2 sips",
  "Everyone who has met someone famous drinks",
  "Make an animal sound or drink",
  "Everyone who has read a book recently drinks",
  "The person on your right drinks",
  "Everyone who has played sports today drinks",
  "Share a random compliment or drink",
  "Everyone who likes pizza drinks",
  "The card picker drinks if they smile",
  "Everyone who has worn sunglasses today drinks",
  "Act like a superhero or drink",
  "Everyone who has taken a selfie today drinks",
  "The card picker chooses someone to tell a funny story",
  "Everyone who has drunk coffee today drinks",
  "Do a funny dance or drink",
  "Everyone who has been to a party this month drinks",
  "The card picker drinks if they can touch their toes",
  "Everyone who has seen a movie this week drinks",
  "Make a silly face or drink",
  "Everyone who has ever dyed their hair drinks",
  "The card picker picks someone to swap a sip with",
  "Everyone who has stayed up past midnight drinks",
  "Act like a celebrity or drink",
  "Everyone who has ever lost their phone drinks",
  "The card picker drinks if they have a sibling",
  "Everyone who has been late to work or school drinks",
  "Share your favorite embarrassing story or drink",
  "Everyone who has watched a horror movie alone drinks",
  "The card picker chooses someone to do a silly dance",
  "Everyone who has ever been in a taxi drinks",
  "Do a funny impression or drink",
  "Everyone who has ever pulled a prank drinks",
  "Everyone who has ever gone camping drinks",
  "Show your best dance move or drink",
  "Everyone who has ever been on a road trip drinks",
  "The card picker drinks if they have a pet",
  "Everyone who has tried a new drink this month drinks",
  "Say a joke or drink",
  "Everyone who has ever eaten fast food today drinks",
  "The card picker chooses someone to swap seats",
  "Everyone who has ever been to a theme park drinks",
  "Imitate your favorite movie character or drink",
  "Everyone who has stayed up past 2 AM drinks",
  "The card picker drinks twice if they laughed",
  "Everyone who has ever skipped class or work drinks",
  "Tell a funny story about school or drink",
  "Everyone who has ever been on a plane drinks",
  "Do a tongue twister or drink",
  "Everyone who has ever met a celebrity drinks",
  "The card picker drinks if wearing socks",
  "Everyone who has ever sung in a public place drinks",
  "Everyone who has ever gotten a speeding ticket drinks",
  "The card picker chooses someone to compliment",
  "Everyone who has ever failed a test drinks",
  "Everyone who has ever dyed their hair a crazy color drinks",
  "Everyone who has ever been on a cruise drinks",
  "The card picker drinks if they own a bike",
  "Everyone who has ever eaten something spicy drinks",
  "Pretend to be an animal or drink",
  "Everyone who has ever had a crush on a coworker drinks",
  "The card picker drinks and chooses someone to take a sip",
  "Everyone who has ever forgotten an important date drinks",
  "Tell a secret or drink",
  "Everyone who has ever been to a wedding drinks",
  "Everyone who has ever made a TikTok drinks",
  "The card picker chooses someone to tell a joke",
  "Everyone who has ever lied about their age drinks",
  "Do 10 squats or drink",
  "Everyone who has ever been to a beach drinks",
  "The card picker drinks if wearing a watch",
  "Everyone who has ever sent a risky text drinks",
  "Sing a line from a song or drink",
  "Everyone who has ever baked something drinks",
  "The card picker chooses someone to do a silly challenge",
  "Everyone who has ever played spin the bottle drinks",
  "Everyone who has ever forgotten someone’s birthday drinks",
  "Everyone who has ever been in a car accident drinks",
  "Share your worst date story or drink",
  "Everyone who has ever gone skinny dipping drinks",
  "The card picker chooses someone to swap drinks",
  "Everyone who has ever stayed out past midnight drinks",
  "Everyone who has ever binge-watched a series drinks",
  "Do your best impression or drink",
  "Everyone who has ever flirted with a stranger drinks",
  "Everyone who has ever sent a text by accident drinks",
  "Everyone who has ever gotten caught sneaking out drinks",
  "The card picker chooses someone to act like an animal",
  "Everyone who has ever done karaoke sober drinks",
  "Everyone who has ever forgotten where they parked drinks",
  "The card picker drinks if wearing blue",
  "Everyone who has ever pulled an all-nighter drinks",
  "Tell a funny story about work or school or drink",
  "Everyone who has ever tried a new hobby this month drinks",
  "The card picker drinks if they laughed in the last minute",
  "Everyone who has ever played truth or dare drinks",
  "Do a silly dance or drink",
  "Everyone who has ever worn a costume drinks",
  "The card picker chooses someone to sing a line from a song",
  "Everyone who has ever cheated in a game drinks",
  "Share your favorite childhood memory or drink",
  "Everyone who has ever eaten dessert before dinner drinks",
  "The card picker drinks if they have a tattoo",
  "Everyone who has ever played a board game drinks",
  "Everyone who has ever laughed so hard they cried drinks",
  "Everyone who has ever been kicked out of a bar drinks",
  "Everyone who has ever pranked someone drinks",
  "The card picker drinks if wearing glasses",
  "Everyone who has ever forgotten to do homework/drinks",
  "Tell a funny joke or drink",
    "Everyone who has ever been on a blind date drinks",
  "The card picker drinks if they have ever lied about their age",
  "Everyone who has ever sent a flirty DM by accident drinks",
  "Do a funny dance move or drink",
  "Everyone who has ever gotten a haircut they regretted drinks",
  "Everyone who has ever ghosted someone drinks",
  "The card picker chooses someone to tell a secret",
  "Everyone who has ever forgotten an important event drinks",
  "Share a funny story from school or drink",
  "Everyone who has ever been on a road trip without planning drinks",
  "Everyone who has ever kissed someone on a dare drinks",
  "Everyone who has ever flirted with a coworker drinks",
  "Everyone who has ever broken something and blamed someone else drinks",
  "Share an embarrassing moment or drink",
  "Everyone who has ever played a drinking card game drinks",
  "The card picker drinks if they have a tattoo or piercing",
  "Everyone who has ever snuck into a movie drinks",
  "Everyone who has ever lied to get out of work drinks",
  "The card picker chooses someone to do 5 jumping jacks",
  "Everyone who has ever danced in public drinks",
  "Everyone who has ever had a wardrobe malfunction drinks",
  "Everyone who has ever sent a risky photo drinks",
  "Everyone who has ever crashed a party drinks",
  "Everyone who has ever flirted to get free drinks drinks",
  "The card picker drinks if they have ever dyed their hair a crazy color",
  "Everyone who has ever pretended to know a celebrity drinks",
  "Share a random fun fact or drink",
  "Everyone who has ever stayed in pajamas all day drinks",
  "Everyone who has ever kissed more than one person in a night drinks",
  "Act like an animal or drink",
  "Everyone who has ever gotten lost in a city drinks",
  "The card picker drinks if they own a pet",
  "Everyone who has ever lied on a dating app drinks",
  "Everyone who has ever made a fake social media account drinks",
  "Everyone who has ever been skydiving or bungee jumping drinks",
  "The card picker drinks if wearing red",
  "Everyone who has ever crashed a wedding drinks",
  "Share a secret or drink",
  "The card picker chooses someone to mimic a celebrity",
  "Everyone who has ever sent a text to the wrong person drinks",
  "Everyone who has ever flirted on social media drinks",
  "Everyone who has ever played a drinking game drinks",
  "Do 5 pushups or drink",
  "Everyone who has ever stayed out past 3 AM drinks",
  "Everyone who has ever danced on a table drinks",
  "Everyone who has ever sent a risky text by accident drinks",
  "Everyone who has ever been kicked out of a club drinks",
  "Everyone who has ever eaten something off the floor drinks",
  "Everyone who has ever pretended to like a gift drinks",
  "The card picker drinks if wearing a necklace",
  "Everyone who has ever lied to a friend drinks",
  "Everyone who has ever cried during a movie drinks",
  "Everyone who has ever had a crush on a friend's sibling drinks",
  "Do 10 jumping jacks or drink",
  "Everyone who has ever flopped a group project drinks",
  "Everyone who has ever stayed up all night partying drinks",
  "The card picker chooses someone to dance for 5 seconds",
  "Everyone who has ever lied to get out of a meeting drinks",
  "The card picker drinks if they have ever sent a text by mistake",
  "Do a silly dance for 5 seconds or drink",
  "Everyone who has ever forgotten an anniversary drinks",
  "The card picker chooses someone to tell a funny joke",
  "Everyone who has ever flirted with a stranger on social media drinks",
  "Act like your favorite movie character or drink",
  "Everyone who has ever pulled a prank on a friend drinks",
  "Sing the chorus of your favorite song or drink",
  "The card picker chooses someone to do 10 squats",
  "Do your best impression of a celebrity or drink",
  "The card picker drinks if they are wearing a watch",
  "Everyone who has ever been on a roller coaster drinks",
  "Do a tongue twister without messing up or drink",
  "The card picker drinks if they are wearing glasses",
  "Everyone who has ever had a crush on a friend’s sibling drinks",
  "Everyone who has ever been on a blind date drinks",
  "Everyone who has ever danced in the rain drinks",
  "Pretend to speak in a silly accent or drink",
  "Everyone who has ever flirted with a bartender drinks",
  "Everyone who has ever been kicked out of a party drinks",
  "Everyone who has ever danced on a table or bar drinks",
  "The card picker drinks if they smiled in the last minute",
  "Everyone who has ever stayed awake all night drinks",
  "Act like your favorite cartoon character or drink",
  "Everyone who has ever flirted with a stranger drinks"
];