export const neverHaveIEverQuestions: string[] = [
  "Never have I ever forgotten my own phone number",
  "Never have I ever locked myself out of my house",
  "Never have I ever pretended my phone was dead",
  "Never have I ever ignored a call and texted instead",
  "Never have I ever snoozed an alarm more than five times",
  "Never have I ever stayed up all night watching shows",
  "Never have I ever rewatched the same series twice",
  "Never have I ever Googled something obvious",
  "Never have I ever practiced a conversation beforehand",
  "Never have I ever laughed at the wrong moment",

  "Never have I ever forgotten why I entered a room",
  "Never have I ever sent a message and regretted it instantly",
  "Never have I ever stalked someone’s social media",
  "Never have I ever accidentally liked an old post",
  "Never have I ever screenshotted a conversation",
  "Never have I ever pretended not to see a message",
  "Never have I ever eaten dessert before dinner",
  "Never have I ever eaten food meant for someone else",
  "Never have I ever stayed in bed all day",
  "Never have I ever worn pajamas outside",
  "Never have I ever worn the same clothes two days in a row",
  "Never have I ever forgotten an important birthday",
  "Never have I ever lied about being busy",
  "Never have I ever complained about being tired after sleeping late",
  "Never have I ever talked to myself out loud",
  "Never have I ever lost my keys",
  "Never have I ever lost my wallet",
  "Never have I ever panicked after losing my phone",
  "Never have I ever dropped my phone on my face",
  "Never have I ever fallen asleep while texting",
  "Never have I ever pretended to understand something",
  "Never have I ever laughed at a joke I didn’t get",
  "Never have I ever Googled myself",
  "Never have I ever judged someone’s music taste",
  "Never have I ever eaten expired food",
  "Never have I ever burned food while cooking",
  "Never have I ever forgotten food on the stove",
  "Never have I ever eaten straight from the container",
  "Never have I ever taken food without asking",
  "Never have I ever eaten midnight snacks",
  "Never have I ever skipped a meal unintentionally",
  "Never have I ever ordered too much food",
  "Never have I ever pretended to like a gift",
  "Never have I ever returned a gift secretly",
  "Never have I ever lied to avoid plans",
  "Never have I ever canceled plans last minute",
  "Never have I ever stayed longer just to be polite",
  "Never have I ever left early without saying goodbye",
  "Never have I ever taken a fake sick day",
  "Never have I ever worked when I should’ve rested",
  "Never have I ever procrastinated until the last minute",
  "Never have I ever crammed for a test",
  "Never have I ever fallen asleep during class",
  "Never have I ever fallen asleep during a meeting",
  "Never have I ever zoned out mid-conversation",
  "Never have I ever nodded without listening",
  "Never have I ever misunderstood instructions",
  "Never have I ever blamed autocorrect",
  "Never have I ever typed a message and deleted it",
  "Never have I ever overthought a reply",
  "Never have I ever refreshed a page waiting for a message",
  "Never have I ever checked my phone with no notifications",
  "Never have I ever charged my phone in public",
  "Never have I ever borrowed a charger from a stranger",
  "Never have I ever used public Wi-Fi",
  "Never have I ever forgotten a password",
  "Never have I ever reset the same password multiple times",
  "Never have I ever written a reminder and ignored it",
  "Never have I ever lost track of time online",
  "Never have I ever stayed up past 3 AM",
  "Never have I ever woken up late accidentally",
  "Never have I ever rushed out without breakfast",
  "Never have I ever skipped showering for a day",
  "Never have I ever worn mismatched socks",
  "Never have I ever worn clothes inside out",
  "Never have I ever spilled food on myself",
  "Never have I ever spilled a drink on someone",
  "Never have I ever tripped in public",
  "Never have I ever pretended nothing happened",
  "Never have I ever laughed at myself",
  "Never have I ever waved at the wrong person",
  "Never have I ever mistaken a stranger for someone I know",
  "Never have I ever walked into the wrong room",
  "Never have I ever taken the wrong seat",
  "Never have I ever stood on the wrong line",
  "Never have I ever gone the wrong direction",
  "Never have I ever missed my stop",
  "Never have I ever gotten lost using GPS",
  "Never have I ever asked for directions",
  "Never have I ever ignored directions",
  "Never have I ever packed too much for a trip",
  "Never have I ever forgotten something important while traveling",
  "Never have I ever unpacked and repacked",
  "Never have I ever traveled without a plan",
  "Never have I ever booked something last minute",
  "Never have I ever missed a flight or bus",
  "Never have I ever fallen asleep while traveling",
  "Never have I ever taken photos I never posted",
  "Never have I ever deleted photos immediately",
  "Never have I ever taken blurry photos",
  "Never have I ever kept screenshots for years",
  "Never have I ever run out of storage",
  "Never have I ever bought something I didn’t need",
  "Never have I ever impulse-bought something",
  "Never have I ever regretted a purchase",
  "Never have I ever returned something late",
  "Never have I ever lost a receipt",
  "Never have I ever forgotten what I ordered",
  "Never have I ever waited too long to decide",
  "Never have I ever changed my mind last second",
  "Never have I ever talked myself out of something",
  "Never have I ever said yes when I wanted to say no",
  "Never have I ever avoided confrontation",
  "Never have I ever apologized first",
  "Never have I ever over-apologized",
  "Never have I ever felt awkward for no reason",
  "Never have I ever felt secondhand embarrassment",
  "Never have I ever laughed silently",
  "Never have I ever laughed way too loud",
  "Never have I ever cried from laughing",
  "Never have I ever cried during a movie",
  "Never have I ever cried during a show",
  "Never have I ever cried over something small",
  "Never have I ever gotten emotional unexpectedly",
  "Never have I ever felt nostalgic suddenly",
  "Never have I ever missed someone unexpectedly",
  "Never have I ever smiled at a memory",
  "Never have I ever replayed a moment in my head",
  "Never have I ever wished I handled something differently",
  "Never have I ever learned from a mistake",
  "Never have I ever forgotten why I opened my phone",
  "Never have I ever typed a long message and deleted it all",
  "Never have I ever checked the fridge multiple times hoping new food appeared",
  "Never have I ever eaten something just because it was there",
  "Never have I ever pretended to hear someone when I didn’t",
  "Never have I ever laughed without knowing why everyone else was laughing",
  "Never have I ever searched how to pronounce a word before saying it",
  "Never have I ever practiced saying my own name",
  "Never have I ever avoided eye contact on purpose",
  "Never have I ever pretended to be busy to avoid small talk",
  "Never have I ever stayed in the bathroom longer to avoid people",
  "Never have I ever refreshed an app waiting for a reply",
  "Never have I ever checked the time and immediately forgot it",
  "Never have I ever lost something that was in my hand",
  "Never have I ever blamed technology for my mistake",
  "Never have I ever restarted a device hoping it would fix everything",
  "Never have I ever Googled a word I already knew",
  "Never have I ever misunderstood song lyrics for years",
  "Never have I ever hummed a song without knowing its name",
  "Never have I ever replayed a song on repeat",
  "Never have I ever skipped an intro only to rewind it",
  "Never have I ever binge-watched instead of sleeping",
  "Never have I ever stayed awake saying “one more episode”",
  "Never have I ever forgotten what day of the week it was",
  "Never have I ever mixed up AM and PM",
  "Never have I ever set multiple alarms just in case",
  "Never have I ever turned off an alarm in my sleep",
  "Never have I ever woken up more tired than before",
  "Never have I ever stayed in bed scrolling too long",
  "Never have I ever checked my phone immediately after waking up",
  "Never have I ever checked my phone before sleeping",
  "Never have I ever eaten breakfast food at night",
  "Never have I ever eaten dinner food for breakfast",
  "Never have I ever eaten something cold instead of reheating it",
  "Never have I ever burned my mouth because I was impatient",
  "Never have I ever underestimated how spicy food was",
  "Never have I ever eaten something I didn’t like to be polite",
  "Never have I ever picked food out of a dish",
  "Never have I ever eaten too fast and regretted it",
  "Never have I ever ordered the same thing every time",
  "Never have I ever changed my order at the last second",
  "Never have I ever forgotten what I went to the store for",
  "Never have I ever gone shopping without buying what I needed",
  "Never have I ever bought something just because it was on sale",
  "Never have I ever regretted buying something immediately",
  "Never have I ever kept something just in case",
  "Never have I ever owned something I never used",
  "Never have I ever lost something and found it later in a weird place",
  "Never have I ever blamed someone else for losing something",
  "Never have I ever searched everywhere except where it actually was",
  "Never have I ever arrived too early and waited awkwardly",
  "Never have I ever arrived late and blamed traffic",
  "Never have I ever checked directions multiple times",
  "Never have I ever missed a turn even with GPS",
  "Never have I ever pretended to know where I was going",
  "Never have I ever walked confidently in the wrong direction",
  "Never have I ever taken the stairs to avoid people",
  "Never have I ever taken the elevator for one floor",
  "Never have I ever avoided someone I recognized",
  "Never have I ever hoped someone wouldn’t recognize me",
  "Never have I ever forgotten someone I already met",
  "Never have I ever avoided saying someone’s name because I forgot it",
  "Never have I ever nodded just to end a conversation",
  "Never have I ever wished a conversation would end",
  "Never have I ever overexplained something simple",
  "Never have I ever explained something badly",
  "Never have I ever corrected someone and felt awkward",
  "Never have I ever realized too late I misunderstood something",
  "Never have I ever replayed an awkward moment in my head",
  "Never have I ever cringed at my past self",
  "Never have I ever wished I could redo a conversation",
  "Never have I ever said something and instantly regretted it",
  "Never have I ever spoken before thinking",
  "Never have I ever stayed quiet to avoid conflict",
  "Never have I ever agreed just to keep the peace",
  "Never have I ever changed my opinion after hearing someone else",
  "Never have I ever doubted a decision right after making it",
  "Never have I ever trusted my gut and been right",
  "Never have I ever trusted my gut and been wrong",
  "Never have I ever learned something the hard way",
  "Never have I ever forgotten where I parked my car",
  "Never have I ever talked to a pet like it understands me",
  "Never have I ever named an inanimate object",
  "Never have I ever replayed an argument in my head",
  "Never have I ever refreshed social media out of boredom",
  "Never have I ever stayed up late scrolling for no reason",
  "Never have I ever lied about liking a movie",
  "Never have I ever pretended to finish a task I didn’t",
  "Never have I ever avoided eye contact in public",
  "Never have I ever pretended to be busy on my phone",
  "Never have I ever checked my reflection in a dark screen",
  "Never have I ever forgotten to reply for days",
  "Never have I ever replied instantly then regretted it",
  "Never have I ever muted a group chat",
  "Never have I ever left a group chat quietly",
  "Never have I ever re-read old messages",
  "Never have I ever felt awkward sending a follow-up text",
  "Never have I ever typed lol without laughing",
  "Never have I ever overused emojis",
  "Never have I ever misunderstood sarcasm",
  "Never have I ever used Google Maps for a very short walk",
  "Never have I ever forgotten why I opened an app",
  "Never have I ever watched videos longer than planned",
  "Never have I ever skipped an intro then went back",
  "Never have I ever binge-watched unintentionally",
  "Never have I ever watched something just because it was trending",
  "Never have I ever abandoned a show halfway",
  "Never have I ever watched something on 1.5x speed",
  "Never have I ever fallen asleep with a video playing",
  "Never have I ever woken up confused about the time",
  "Never have I ever checked the time repeatedly",
  "Never have I ever stayed in bed after waking up",
  "Never have I ever forgotten what day it was",
  "Never have I ever ignored an alarm completely",
  "Never have I ever rushed while already late",
  "Never have I ever blamed traffic for being late",
  "Never have I ever arrived too early",
  "Never have I ever waited awkwardly for someone",
  "Never have I ever pretended not to notice someone",
  "Never have I ever avoided someone I knew",
  "Never have I ever smiled at a stranger accidentally",
  "Never have I ever misunderstood a gesture",
  "Never have I ever felt awkward in silence",
  "Never have I ever talked too much when nervous",
  "Never have I ever overshared accidentally",
  "Never have I ever immediately regretted oversharing",
  "Never have I ever changed the subject quickly",
  "Never have I ever laughed just to fill silence",
  "Never have I ever forgotten someone’s name mid-conversation",
  "Never have I ever used a nickname to avoid a name",
  "Never have I ever forgotten an appointment",
  "Never have I ever double-booked plans",
  "Never have I ever canceled because I felt lazy",
  "Never have I ever stayed home instead of going out",
  "Never have I ever enjoyed canceling plans",
  "Never have I ever felt relief after canceling",
  "Never have I ever said maybe when I meant no",
  "Never have I ever changed my order last second",
  "Never have I ever regretted not ordering something",
  "Never have I ever tasted someone else’s food",
  "Never have I ever eaten too fast",
  "Never have I ever burned my mouth on hot food",
  "Never have I ever eaten something despite disliking it",
  "Never have I ever skipped vegetables intentionally",
  "Never have I ever eaten snacks instead of meals",
  "Never have I ever eaten just because I was bored",
  "Never have I ever forgotten to drink water all day",
  "Never have I ever bought food then forgot about it",
  "Never have I ever let food expire unused",
  "Never have I ever opened the fridge without a plan",
  "Never have I ever made a mess while cooking",
  "Never have I ever followed a recipe incorrectly",
  "Never have I ever improvised a recipe badly",
  "Never have I ever tasted food mid-cooking repeatedly",
  "Never have I ever eaten standing up",
  "Never have I ever eaten while distracted",
  "Never have I ever forgotten to save my work",
  "Never have I ever lost progress due to a crash",
  "Never have I ever closed a tab accidentally",
  "Never have I ever opened too many tabs",
  "Never have I ever searched something embarrassing",
  "Never have I ever deleted browsing history",
  "Never have I ever typed the wrong search term",
  "Never have I ever clicked the wrong link",
  "Never have I ever downloaded something unnecessary",
  "Never have I ever ignored an update",
  "Never have I ever postponed an update for weeks",
  "Never have I ever accidentally turned something off",
  "Never have I ever struggled with a simple setting",
  "Never have I ever asked for help after giving up",
  "Never have I ever fixed something by restarting",
  "Never have I ever unplugged and replugged something",
  "Never have I ever blamed technology unfairly",
  "Never have I ever felt proud fixing something simple",
  "Never have I ever Googled how to do something basic",
  "Never have I ever watched a tutorial halfway",
  "Never have I ever started something and not finished",
  "Never have I ever abandoned a hobby quickly",
  "Never have I ever bought supplies I never used",
  "Never have I ever planned something I didn’t start",
  "Never have I ever procrastinated productively",
  "Never have I ever cleaned instead of working",
  "Never have I ever reorganized instead of starting",
  "Never have I ever made a to-do list and ignored it",
  "Never have I ever rewritten a to-do list",
  "Never have I ever checked something off early",
  "Never have I ever overestimated my motivation",
  "Never have I ever underestimated how long something takes",
  "Never have I ever rushed near the deadline",
  "Never have I ever felt accomplished over something small",
  "Never have I ever celebrated finishing a task",
  "Never have I ever rewarded myself prematurely",
  "Never have I ever promised myself I’d do better tomorrow",
  "Never have I ever said this is the last time",
  "Never have I ever repeated the same mistake",
  "Never have I ever laughed about it later"
];